/* 1주차 요약 슬라이드(교안) — docs/SLIDE_GUIDE.md 참고 */
COURSE.addSlides({
  'w1-0': {
    intro: '<p>“앞으로 5주 동안 컴퓨터에게 ‘보는 법’을 가르쳐 봅니다. 설치는 필요 없고, 브라우저만 있으면 됩니다.” 스마트폰 얼굴 잠금, 주차장 번호판 인식처럼 카메라가 무언가를 “알아보는” 경험을 한두 명에게 물어보며 시작하세요. (도입 2분)</p>',
    goalsNotes: '<p>오늘은 본격적인 영상처리 전 <b>준비운동</b> 시간입니다. 환경을 손에 익히고, “이미지는 숫자 배열”이라는 한 문장을 꼭 가져가게 하세요. 마지막 목표(검은 캔버스 칠하기)가 오늘의 도착점입니다.</p>',
    slides: [
      { title: 'OpenCV 란?',
        points: ['<b>Open Source Computer Vision</b> 라이브러리', '1999 인텔 시작 · <b>2,500+</b> 알고리즘', 'OpenCV-Python = C++ 본체를 감싼 <b>wrapper</b>', '“문법은 쉬운 Python, 속도는 빠른 C++”', '이미지를 <b>NumPy 배열</b>로 주고받음'],
        image: 'opencv-logo.png', caption: 'import cv2 as cv',
        notes: '<p>“OpenCV 는 사진 보정 앱, 공장 불량 검사, 자율주행, 의료 영상까지 거의 모든 영상 분야에서 쓰이는 무료 라이브러리예요.”</p><p>마지막 줄이 오늘의 핵심 복선입니다. “OpenCV-Python 에서 이미지는 결국 NumPy 배열이라서, NumPy 를 조금만 알면 이미지를 마음대로 다룰 수 있다”고 강조하세요. (3분)</p>' },
      { title: '5주 과정 로드맵',
        table: { head: ['주차', '주제', '대표 내용'], rows: [
          ['1주차', '입문 · GUI · 코어 연산', '입출력, 그리기, 마우스·트랙바, 픽셀 연산'],
          ['2주차', 'Image Processing Ⅰ', '색 공간, 기하 변환, 임계처리, 블러'],
          ['3주차', 'Image Processing Ⅱ', '엣지, 컨투어, 히스토그램, 허프 변환'],
          ['4주차', '프로젝트 Ⅰ', '가이드 프로젝트 4개, 팀 기획'],
          ['5주차', '프로젝트 Ⅱ', '구현·튜닝, 발표와 회고'],
        ] },
        notes: '<p>“앞 3주는 기능을 하나씩 배우고, 뒤 2주는 그 기능을 조합해 문서 스캐너, 동전 세기, 웹캠 페인터 같은 프로그램을 직접 만듭니다.”</p><p>매 교시가 <b>개념 → 예제 실행 → 실습 → 퀴즈</b> 순서라는 것도 함께 안내하세요. 예제는 읽지만 말고 숫자를 바꿔 여러 번 실행하라고 당부합니다. (2분)</p>' },
      { title: '웹 실습 환경 화면 구성',
        points: ['설치 없이 <b>브라우저 안에서</b> Python + OpenCV', '왼쪽: 주차·교시 목록, 진도, 검색', '가운데: 강의 내용 + <b>코드 에디터</b>', '오른쪽: 입력 소스 · 트랙바 · 결과 창 · <b>콘솔</b>', '첫 로딩 “Python 준비 중…” 수십 초'],
        tip: '웹캠이 없어도 OK — 입력 소스를 🎞️ 동영상으로 고르면 됩니다',
        notes: '<p>화면을 직접 띄우고 세 영역을 손으로 가리키며 설명하세요. “오른쪽 위가 준비 완료로 바뀌어야 ▶ 실행 버튼이 켜집니다.”</p><p>학생 화면에서 로딩이 끝났는지 손을 들어 확인하고 넘어가세요. 로딩이 느린 학생이 있으면 새로고침보다는 조금 기다리게 합니다. (3분)</p>' },
      { title: '꼭 알아야 할 버튼',
        table: { head: ['버튼 / 기능', '하는 일'], rows: [
          ['<b>▶ 실행</b> · <code>Ctrl+Enter</code>', '에디터 코드 실행'],
          ['<b>■ 정지</b> · <b>↺ 초기화</b>', '실시간 처리 멈춤 · 예제 코드로 되돌리기'],
          ['<b>입력 소스</b> 선택', '샘플 이미지 · 🎞️ 동영상 · 업로드 · 📷 웹캠'],
          ['<b>📷 웹캠 켜기</b> · <b>📸 스냅샷</b>', '웹캠 켜기(권한 허용) · webcam.png 저장'],
          ['<b>⬆ 업로드</b>', '내 이미지·동영상(mp4/webm) 추가'],
          ['<b>콘솔</b>', 'print 출력 · 오류 메시지 · 저장 파일 링크'],
        ] },
        notes: '<p>발문: “코드를 실수로 망가뜨렸다면 어떤 버튼을 누를까요?” → ↺ 초기화.</p><p>입력 소스 선택 상자를 열어 샘플 이미지와 🎞️ 동영상 목록을 한 번 보여 주세요. 웹캠·동영상은 3교시에 본격적으로 씁니다. (2분)</p>' },
      { title: '첫 실행: 버전 확인', example: 0,
        points: ['▶ 실행 → 콘솔에 OpenCV · NumPy 버전 출력'],
        notes: '<p>“콘솔에 버전 숫자가 찍혔다면 여러분 환경은 준비 완료입니다.” 전원이 성공했는지 확인하세요.</p><p>문자열을 바꿔 자기 이름을 출력해 보게 하면 에디터 수정 → 재실행 흐름을 자연스럽게 익힙니다. (2분)</p>' },
      { title: 'OpenCV 에 필요한 Python 문법',
        points: ['<b>리스트</b> <code>[1, 2, 3]</code>: 바꿀 수 있는 목록', '<b>튜플</b> <code>(x, y)</code> · <code>(B, G, R)</code>: 좌표와 색', '<b>함수</b> <code>def</code>: 마우스 · 트랙바 · process 에 필수', '<b>여러 값 받기</b> <code>ret, frame = cap.read()</code>', '<b>별명</b> <code>import cv2 as cv</code>'],
        notes: '<p>문법 수업이 아니라 “OpenCV 코드를 읽기 위한 최소한”이라고 선을 그어 주세요.</p><p>발문: “색을 (255, 0, 0) 으로 쓰면 무슨 색일까요?” → OpenCV 는 B, G, R 순서라 <b>파랑</b>. 1교시에서 이유를 배운다고 예고합니다. (3분)</p>' },
      { title: '리스트 · 튜플 · 함수 복습', example: 1,
        points: ['튜플 풀기 <code>x, y = point</code> · 값 2개 돌려주는 함수'],
        notes: '<p>실행 후 <code>lo, hi = min_max(scores)</code> 줄을 가리키며 “나중에 <code>ret, frame = cap.read()</code> 가 바로 이 모양”이라고 연결하세요.</p><p>Python 이 처음인 학생이 있으면 들여쓰기(스페이스 4칸)가 문법이라는 점을 짚어 줍니다. (3분)</p>' },
      { title: 'NumPy 배열: 꼭 알아야 할 3가지',
        points: ['<code>arr.shape</code>: 모양 · <code>(3, 4)</code> = 3행 4열', '<code>arr.dtype</code>: 자료형 · 이미지는 <b>uint8</b> (0~255)', '슬라이싱 <code>arr[행:행, 열:열]</code> · 끝 번호 미포함', '<b>벡터화</b>: <code>arr * 2</code> 는 반복문 없이 전체 계산'],
        notes: '<p>“이미지 처리에서 파이썬 for 문 대신 NumPy·OpenCV 함수를 쓰는 이유가 벡터화의 속도 차이입니다. 8교시에 직접 시간을 재 봅니다.”</p><p>발문: “uint8 에 300 을 넣을 수 있을까요?” → 없다, 0~255 만. (2분)</p>' },
      { title: 'shape · dtype 확인하기', example: 2,
        points: ['2차원 배열 = 표 · <code>b[1, 2]</code> = 1행 2열'],
        notes: '<p>실행 결과에서 <code>b.shape</code> 가 (2, 3) 으로 나오는 것을 보고 “행이 먼저, 열이 나중”을 확인시키세요.</p><p><code>np.zeros((2, 5), dtype=np.uint8)</code> 는 곧 “검은 이미지 만들기”에 그대로 쓰인다고 예고합니다. (3분)</p>' },
      { title: '슬라이싱으로 꺼내고 바꾸기', example: 3,
        points: ['<code>m[0:2, 1:4]</code> 꺼내기 · <code>m[1:3, 1:3] = 0</code> 대입'],
        notes: '<p>실행 전에 발문: “<code>m[0:2, 1:4]</code> 는 몇 행 몇 열일까요?” → 2행 3열 (끝 번호 미포함). 예측 후 실행해 맞춰 보게 하세요.</p><p>“슬라이스에 값을 대입하면 그 부분만 바뀐다” — 이것이 잠시 뒤 이미지 색칠의 원리입니다. (3분)</p>' },
      { title: '이미지는 NumPy 배열이다',
        points: ['흑백: shape <code>(높이, 너비)</code> · 0=검정 ~ 255=흰색', '컬러: shape <code>(높이, 너비, 3)</code> · <b>BGR</b> 순서', '검은 이미지 = <code>np.zeros((h, w, 3), np.uint8)</code>', '영역 칠하기 = 슬라이스에 <code>(B, G, R)</code> 대입'],
        warn: '배열은 행부터 img[y, x], 좌표는 x부터 (x, y)',
        notes: '<p>“이미지를 만드는 것도, 색칠하는 것도 방금 배운 NumPy 문법 그대로예요.”</p><p>shape 가 (높이, 너비) 순서라는 점과, 뒤에서 배울 그리기 함수 좌표는 (x, y) 라는 점을 미리 대비시켜 두세요. 초보자가 가장 많이 헷갈리는 부분입니다. (2분)</p>' },
      { title: '검은 캔버스에 색칠하기', example: 4,
        points: ['<code>img[50:150, 50:200] = (0, 0, 255)</code> → 빨강'],
        notes: '<p>실행 후 결과 창에 마우스를 올려 빨간 영역의 값이 (0, 0, 255) 인지 확인시키세요.</p><p>발문: “초록 사각형이 빨간 사각형을 덮은 이유는?” → 나중에 대입한 값이 덮어씀. 색 값을 바꿔 자기만의 도형을 칠해 보게 하세요. (4분)</p>' },
      { title: '사진도 배열이다', example: 5,
        points: ['<code>cv.imread</code> 로 읽고 슬라이싱으로 자르기', '<code>webcv.get_input()</code>: 입력 소스 이미지 가져오기 (웹 전용)'],
        notes: '<p>“messi5.jpg 도 (342, 548, 3) 모양의 숫자 배열일 뿐입니다.” part 창이 원본의 어느 부분인지 찾아보게 하세요.</p><p>입력 소스를 다른 샘플이나 📷 웹캠으로 바꾸고 다시 실행해 my input 창이 바뀌는 것을 보여 주세요. <code>webcv</code> 는 이 웹 환경에만 있는 도우미라는 점도 밝혀 둡니다. (3분)</p>' },
      { title: '(참고) 내 PC 설치 · 오류 읽는 법',
        points: ['<code>pip install opencv-python</code> (+ matplotlib)', '데스크톱: <code>imshow</code> 는 새 창, <code>waitKey</code> 필요', '오류 메시지는 <b>마지막 줄</b>부터 읽기', '흔한 오류: NameError · IndentationError · SyntaxError'],
        notes: '<p>설치는 과정이 끝난 뒤 집에서 해 보라고 안내만 하고 넘어가세요. 명령은 문서 보기의 “설치 명령” 코드에 있습니다.</p><p>“빨간 오류가 나도 괜찮아요. 맨 아래 줄이 원인을 알려 줍니다.” 이름 오타·들여쓰기·괄호 빠짐이 대부분이라고 안심시키세요. (2분)</p>' },
    ],
    practiceNotes: [
      '<p>열 범위 <code>flag[:, 0:100]</code> 처럼 <b>행은 전체(:)</b>, 열만 나눈다는 점이 핵심입니다. 파랑을 (0, 0, 255) 로 쓰는 BGR 실수가 가장 흔하니, 빨강과 파랑이 좌우로 뒤바뀌어 나오면 색 순서를 확인시키세요.</p>',
      '<p><code>np.arange(256, dtype=np.uint8)</code> 한 줄을 모든 행에 대입하면 브로드캐스팅으로 복사됩니다. 가운데 픽셀 값이 128 로 나오는지 확인하게 하세요. for 문으로 푼 학생에게는 “한 줄로도 된다”고 힌트를 줍니다.</p>',
      '<p>아래·오른쪽은 음수 인덱스 <code>-20:</code> 를 쓰면 크기를 몰라도 됩니다. 결과 창에서 액자 두께가 네 변 모두 같은지, 출력된 shape 가 (342, 548, 3) 인지 확인하세요.</p>',
    ],
    summary: ['OpenCV-Python: C++ 속도 + Python 문법, 이미지는 <b>NumPy 배열</b>', '웹 실습: ▶ 실행(<code>Ctrl+Enter</code>), 입력 소스, 콘솔', 'NumPy 핵심: <code>shape</code> · <code>dtype(uint8)</code> · 슬라이싱', '컬러 이미지 = <code>(높이, 너비, 3)</code>, <b>BGR</b> 순서', '<code>np.zeros</code> + 슬라이스 대입으로 이미지 만들기'],
    next: '<p>“오늘은 이미지가 숫자 배열이라는 걸 코드로 확인했어요. 다음 시간에는 한 걸음 물러서서 <b>픽셀·해상도·흑백과 컬러</b>가 무엇인지, 왜 OpenCV 는 BGR 인지 영상처리의 기초 이론을 눈으로 확인해 봅니다.”</p>',
  },
  'w1-1': {
    intro: '<p>“오늘은 코드를 많이 쓰기 전에, 컴퓨터가 사진을 어떻게 ‘숫자’로 보는지부터 이해해 봅니다.” 휴대폰으로 사진을 찍으면 그 안에 무엇이 저장되는지 한 명에게 물어보며 시작하세요. (도입 2분)</p>',
    goalsNotes: '<p>목표 네 가지를 읽고, 오늘은 <b>외우는 시간이 아니라 눈으로 확인하는 시간</b>이라고 안내합니다. 예제는 모두 ▶ 실행으로 바로 결과를 볼 수 있습니다.</p>',
    slides: [
      { title: '컴퓨터는 사진을 어떻게 볼까?',
        points: ['사람: 한눈에 “공 차는 선수”', '컴퓨터: 수십만 개의 <b>숫자 표</b>', '숫자에서 규칙 찾기 = <b>영상처리</b>', '카메라 센서가 빛의 세기를 숫자로 기록'],
        image: 'messi5.jpg', caption: 'messi5.jpg · 548×342',
        notes: '<p>“여러분은 이 사진에서 공을 바로 찾지만, 컴퓨터가 받는 건 숫자뿐이에요.” 모눈종이 칸마다 색연필 번호를 적은 그림을 비유로 들어 주세요.</p><p>발문: “컴퓨터가 공을 찾으려면 어떤 규칙을 쓰면 될까요?” → 예상 답: 둥근 모양, 흰색/노란색, 주변과 밝기가 다름.</p>' },
      { title: '픽셀(화소)과 좌표',
        points: ['영상 = 픽셀의 <b>격자</b> (2차원 배열)', '원점 (0, 0) = <b>왼쪽 위</b>, y는 아래로 증가', 'OpenCV 함수 좌표: <code>(x, y)</code>', 'NumPy 인덱싱: <code>img[y, x]</code> ← 순서 주의!'],
        warn: '초보자 실수 1위: (x, y) 와 [y, x] 순서 혼동',
        notes: '<p>본문의 8×8 숫자 표(웃는 얼굴)를 문서 보기로 잠깐 보여 주면 효과적입니다. “숫자만으로 얼굴이 보이나요?”</p><p>좌표축이 수학 그래프와 반대(y가 아래로 증가)라는 점을 손으로 가리키며 강조하세요.</p>' },
      { title: '꼭 알아야 할 용어',
        table: { head: ['용어', '뜻', '예'], rows: [
          ['픽셀', '가장 작은 점 하나', 'messi5.jpg = 187,416개'],
          ['해상도', '가로 × 세로 픽셀 수', '1920×1080 (Full HD)'],
          ['채널', '픽셀 하나의 값 개수', '흑백 1 · 컬러 3'],
          ['비트 깊이', '값의 단계 수', '8비트 = 0~255'],
          ['프레임 · fps', '동영상의 한 장 · 초당 장 수', '30fps 1분 = 1,800장'],
        ] },
        notes: '<p>표를 한 줄씩 읽기보다 “1200만 화소 스마트폰 = 약 4000×3000”처럼 학생들이 아는 숫자와 연결하세요. (2분)</p>' },
      { title: '사진을 확대하면 네모 칸이 보인다', example: 0,
        points: ['축구공 16×16 픽셀을 20배 확대 + 밝기 값 출력'],
        notes: '<p>▶ 실행 후 오른쪽 “16x16 확대” 창에 마우스를 올리면 위쪽에 좌표와 B, G, R 값이 나옵니다. 어두운 칸과 밝은 칸의 값을 학생이 직접 읽게 하세요.</p><p>콘솔의 8×8 숫자 배열과 확대 창의 칸이 같은 것이라는 점을 연결합니다. (3분)</p>' },
      { title: '아날로그 → 디지털: 두 번 자르기',
        points: ['<b>샘플링</b>: 공간을 몇 칸으로? → 해상도', '<b>양자화</b>: 밝기를 몇 단계로? → 비트 깊이', '비유: 모눈종이 칸 크기 · 색연필 개수', '보통 채널당 8비트 = 256단계'],
        notes: '<p>“칸이 크면 모자이크가 되고, 색연필이 적으면 그라데이션이 띠처럼 끊깁니다.” 다음 두 예제로 바로 확인한다고 예고하세요.</p>' },
      { title: '샘플링: 해상도를 줄이면?', example: 1,
        points: ['512 → 256 · 64 · 32 · 16 으로 줄였다가 다시 확대'],
        notes: '<p>발문: “몇 픽셀부터 사람 얼굴로 알아볼 수 있나요?” → 대부분 32~64 사이라고 답합니다.</p><p>“실시간 처리에서는 일부러 해상도를 낮춰 속도를 얻는다”는 점을 짧게 언급 (5주차 연결).</p>' },
      { title: '양자화: 밝기 단계를 줄이면?', example: 2,
        points: ['256 · 16 · 4 · 2 단계 비교 → 2단계 = 이진 영상'],
        notes: '<p>16단계에서 볼·배경에 생기는 등고선 같은 띠를 가리켜 보세요. 2단계(검정/흰색)는 2주차 “임계처리”에서 다시 만난다고 연결합니다. (3분)</p>' },
      { title: '흑백(그레이스케일) 영상',
        points: ['픽셀마다 <b>밝기 값 1개</b> · shape <code>(h, w)</code>', '데이터가 컬러의 1/3 → <b>빠르다</b>', '엣지 · 임계처리 · 컨투어의 기본 입력', '이진 영상 = 0과 255 두 값 (마스크)'],
        tip: '흑백으로 바꾸면 색은 되돌릴 수 없어요 (정보 손실)',
        notes: '<p>“왜 굳이 흑백으로 바꿀까요?” → 계산이 빠르고, 모양·윤곽은 밝기만으로 충분하기 때문. 문서 스캔, 글자 인식을 예로 드세요.</p>' },
      { title: '컬러 영상과 빛의 3원색',
        points: ['R · G · B 를 섞는 <b>가산 혼합</b> (섞을수록 밝아짐)', '픽셀마다 숫자 3개 · shape <code>(h, w, 3)</code>', '256³ = 약 <b>1,677만 색</b>', 'OpenCV 는 <b>BGR 순서</b>! <code>(255, 0, 0)</code> = 파랑'],
        warn: 'Matplotlib · 웹 이미지는 RGB → 순서 변환 필요 (다음 교시)',
        notes: '<p>BGR 순서는 초창기 카메라 드라이버·Windows 비트맵 형식의 역사 때문이라고 짧게 설명하세요. 물감(감산 혼합)과 빛(가산 혼합)의 차이를 물어보면 좋습니다.</p>' },
      { title: '빛의 3원색 섞어 보기', example: 3,
        points: ['세 원을 <code>cv.add</code> 로 더해 청록 · 자홍 · 노랑 · 흰색 만들기'],
        notes: '<p>실행 후 콘솔의 BGR 값을 함께 읽습니다. “노랑은 어떤 두 빛을 섞은 걸까요?” → 초록 + 빨강 = [0, 255, 255].</p>' },
      { title: '채널 = 색의 세기 지도', example: 4,
        points: ['fruits.jpg 를 B · G · R 흑백 3장으로 분리'],
        notes: '<p>주황 오렌지가 R 채널에서 밝고 B 채널에서 어둡게 보이는 것을 확인시키세요. 라임은 G 채널에서 상대적으로 밝습니다. (3분)</p>' },
      { title: '컬러 → 흑백 변환의 원리', example: 5,
        points: ['<b>Y = 0.299R + 0.587G + 0.114B</b> · 사람 눈은 초록에 가장 민감'],
        notes: '<p>순수 초록(150)이 순수 파랑(29)보다 훨씬 밝은 회색이 되는 결과를 보여 주세요. 단순 평균 창과 OpenCV 창을 비교하면 하늘·잎의 밝기가 다르게 보입니다.</p>' },
      { title: '영상처리 · 컴퓨터 비전 · AI',
        points: ['<b>영상처리</b>: 영상 → 영상 (보정 · 잡음 제거 · 변환)', '<b>컴퓨터 비전</b>: 영상 → 정보 (개수 · 위치 · 종류)', '<b>딥러닝</b>: 학습으로 인식, 앞뒤 처리는 영상처리', '파이프라인: 입력 → 전처리 → 특징 → 분석 → 표시'],
        notes: '<p>발문: “번호판 글자 읽기는 영상처리일까요, 컴퓨터 비전일까요?” → 컴퓨터 비전(정보 추출), 그 안의 전처리는 영상처리.</p><p>이 과정 5주 흐름이 파이프라인 단계와 대응한다고 짚어 주세요.</p>' },
      { title: '파이프라인 맛보기: 동전 사진', example: 6,
        points: ['흑백 → 블러 → 이진화 · 엣지 → 컨투어 → 결과 표시'],
        notes: '<p>함수 이름은 외우지 않아도 된다고 안심시키세요. “한 단계의 출력이 다음 단계의 입력”이라는 흐름만 창 순서대로 보여 줍니다.</p><p>덩어리가 1개로 나오는 이유(동전이 붙어 있음)를 묻고, 4주차 프로젝트에서 해결한다고 예고합니다.</p>' },
      { title: 'OpenCV 는 어떤 라이브러리?',
        points: ['1999 인텔 연구 프로젝트 → 세계 최대 비전 라이브러리', '<b>2,500+</b> 알고리즘 · <b>Apache 2</b> 무료 라이선스', 'C++ 로 빠르고, Python · Java · 웹(OpenCV.js) 지원', '이 과정의 중심 모듈: <code>imgproc</code>'],
        notes: '<p>OpenCV 공식 소개(opencv.org/about)에 Google · Microsoft · Intel · Sony · Honda · Toyota, NASA 등이 사용한다고 나와 있다고 소개하세요. 연혁 표는 문서 보기에서 참고.</p>' },
      { title: '어디에 쓰일까? 우리 주변의 영상처리',
        table: { head: ['분야', '활용 예', '관련 주차'], rows: [
          ['📱 스마트폰 앱', '문서 스캔 · 파노라마 · 필터', '2 · 4주차'],
          ['🚗 자동차 · 교통', '차선 · 번호판 인식', '3주차'],
          ['🏭 제조 (머신 비전)', '불량 검사 · 개수 세기', '2~4주차'],
          ['🏥 의료', 'X-ray 대비 개선 · 세포 세기', '3주차'],
          ['📹 보안 · 🌾 농업', '움직임 감지 · 과일 선별', '1 · 2주차'],
          ['🎮 AR · ⚽ 스포츠', '얼굴 필터 · 공 추적', '1 · 3주차'],
        ] },
        notes: '<p>“오늘 카메라와 소프트웨어가 여러분 대신 무언가를 본 순간은?” 주차장 번호판 인식, 얼굴 잠금 해제, 영상 통화 배경 흐림 등 학생 경험을 2~3개 받아 보세요. (3분)</p><p>참고 링크(위키백과 · OpenCV 공식)는 문서 보기 맨 아래에 있다고 안내합니다.</p>' },
    ],
    practiceNotes: [
      '<p>좌표는 <code>img[y, x]</code> 순서라는 점을 다시 확인시키세요. 공(노랑)은 R 과 G 가 함께 크게 나오는데, “가장 큰 채널만으로는 노랑을 구분하기 어렵다”는 발견을 끌어내면 좋습니다.</p>',
      '<p>입력 소스를 동영상이나 웹캠으로 바꿔도 된다고 안내하세요. 대부분 16~32단계부터 차이를 느끼기 어렵다고 답합니다.</p>',
      '<p>채널을 뒤집으면 빨강/파랑 줄무늬가 서로 바뀝니다. <code>nbytes</code> 비율이 정확히 3.0 인지 확인하게 하세요.</p>',
    ],
    summary: ['디지털 영상 = <b>픽셀 격자</b>, 좌표는 <code>(x, y)</code> / <code>img[y, x]</code>', '해상도(샘플링)와 밝기 단계(양자화)가 화질을 결정', '흑백 1채널 · 컬러 3채널, OpenCV 는 <b>BGR</b>', '흑백 변환은 초록 가중치가 가장 큰 <b>가중합</b>', '영상처리 = 영상→영상, 컴퓨터 비전 = 영상→정보'],
    next: '<p>“다음 시간에는 오늘 본 숫자 배열을 직접 파일에서 읽고, 화면에 보여주고, 저장해 봅니다. 오늘 경고한 BGR/RGB 순서 문제도 Matplotlib 으로 직접 겪어 봅니다.”</p>',
  },
  'w1-2': {
    intro: '<p>“지난 시간에 이미지가 숫자 격자라는 걸 봤죠? 오늘은 그 숫자를 <b>파일에서 읽고, 화면에 보여주고, 다시 파일로 저장</b>합니다.” 모든 영상처리 프로그램의 시작과 끝이 되는 세 함수라고 동기를 주세요. (도입 1분)</p>',
    goalsNotes: '<p>imread · imshow · imwrite 세 함수와, <b>데스크톱과 웹 환경의 차이</b>, <b>BGR/RGB 문제</b>가 오늘의 핵심입니다. 튜토리얼(데스크톱) 코드를 웹에서 어떻게 바꿔 쓰는지도 함께 익힌다고 안내하세요.</p>',
    slides: [
      { title: '영상처리 프로그램의 뼈대',
        points: ['① <b>읽기</b> → ② 처리 → ③ <b>보여주기</b> → ④ <b>저장</b>', '오늘은 ①③④ — 처리는 다음 교시부터', '<code>cv.imread</code> · <code>cv.imshow</code> · <code>cv.imwrite</code>', '튜토리얼: “Getting Started with Images”'],
        image: 'starry_night.jpg', caption: 'starry_night.jpg — 튜토리얼 예제 이미지',
        notes: '<p>“사진 앱이든 번호판 인식이든 뼈대는 똑같아요. 읽고, 처리하고, 보여주고, 저장합니다.”</p><p>발문: “사진 필터 앱에서 ①~④ 는 각각 무엇일까요?” → 갤러리에서 열기, 필터 적용, 미리보기, 저장 버튼. (2분)</p>' },
      { title: '튜토리얼 원본 코드 읽기 (데스크톱)', example: 0,
        points: ['읽기 → None 확인 → 창 표시 → 키 대기 → s 키면 저장'],
        notes: '<p>실행하지 않고 한 줄씩 소리 내어 읽어 주세요. <code>waitKey(0)</code> 이 “키를 누를 때까지 기다린다”는 것과, 누른 키가 s 이면 저장한다는 흐름만 잡으면 됩니다.</p><p>“<code>cv.samples.findFile</code> 은 데스크톱에서 샘플 파일을 찾는 함수이고, 웹에서는 파일 이름만 쓰면 됩니다.” (2분)</p>' },
      { title: 'cv.imread() 와 flag',
        table: { head: ['flag', '숫자', '결과'], rows: [
          ['<code>cv.IMREAD_COLOR</code> (기본값)', '1', '3채널 BGR, 투명도 버림'],
          ['<code>cv.IMREAD_GRAYSCALE</code>', '0', '1채널 흑백 · shape <code>(h, w)</code>'],
          ['<code>cv.IMREAD_UNCHANGED</code>', '-1', '파일 그대로 · PNG 는 4채널 BGRA'],
        ] },
        notes: '<p>“두 번째 인자로 <b>어떤 모양으로 읽을지</b> 정합니다.” 흑백은 엣지·임계처리처럼 밝기만 필요할 때, UNCHANGED 는 투명 배경 로고를 합성할 때(8교시) 쓴다고 용도를 연결하세요.</p><p>숫자 1, 0, -1 로도 쓸 수 있지만 이름 상수가 읽기 쉽다고 권합니다. (3분)</p>' },
      { title: '이미지 읽고 표시하기 (웹 버전)', example: 1,
        points: ['<code>waitKey(0)</code> 은 웹에서 즉시 -1 · <code>destroyAllWindows</code> 는 무동작'],
        notes: '<p>실행 후 콘솔의 “waitKey 반환값: -1”을 가리키며 “웹에서는 기다리지 않아요. 그래도 데스크톱 코드를 그대로 붙여 넣어도 오류는 나지 않습니다.”</p><p>결과 창은 오른쪽 패널에 카드로 나타나고, 같은 이름으로 imshow 하면 교체된다는 점도 보여 주세요. (3분)</p>' },
      { title: 'flag 에 따라 달라지는 shape', example: 2,
        points: ['같은 로고 PNG → <code>(794, 600, 3)</code> · <code>(794, 600)</code> · <code>(794, 600, 4)</code>'],
        notes: '<p>실행 전에 발문: “흑백으로 읽으면 shape 가 어떻게 될까요?” → 채널 축이 사라진 (794, 600). 예측 후 실행해 확인하세요.</p><p>COLOR 로 읽으면 투명했던 배경이 검정으로 바뀌는 점을 창에서 비교하게 합니다. (3분)</p>' },
      { title: 'imshow · waitKey: 데스크톱 vs 웹',
        table: { head: ['함수', '데스크톱', '웹 실습 환경'], rows: [
          ['<code>cv.imshow(name, img)</code>', '새 창을 띄움', '결과 패널에 카드로 표시'],
          ['<code>cv.waitKey(0)</code>', '키를 누를 때까지 무한 대기', '즉시 -1 반환'],
          ['<code>cv.waitKey(ms)</code>', 'ms 동안 키 입력 대기', '즉시 -1 반환'],
          ['<code>cv.destroyAllWindows()</code>', '열린 창 모두 닫기', '아무 동작 안 함'],
        ] },
        notes: '<p>“데스크톱에서는 창이 실제로 그려지는 순간이 waitKey 가 도는 동안이라, imshow 뒤에 waitKey 가 짝으로 붙어 다닙니다.”</p><p>인터넷에서 찾은 코드에 waitKey 가 보여도 겁먹지 말라고, 웹에서는 무시된다고 정리해 주세요. (3분)</p>' },
      { title: '읽기 실패는 오류 대신 None',
        points: ['파일이 없어도 <code>imread</code> 는 <b>오류를 안 냄</b>', '대신 조용히 <code>None</code> 반환', '그 뒤 <code>img.shape</code> → AttributeError', '확인은 <code>if img is None:</code>'],
        warn: 'NoneType 오류가 보이면 파일 이름 · 확장자 · 대소문자부터 확인',
        notes: '<p>발문: “<code>\'NoneType\' object has no attribute \'shape\'</code> 오류는 진짜 원인이 어디에 있을까요?” → 그 줄이 아니라 <b>imread 줄</b>(파일 이름 오타).</p><p>학생들이 실습 중 가장 자주 만나는 오류이니 이 문장을 꼭 기억시키세요. (2분)</p>' },
      { title: 'None 확인하기', example: 3,
        points: ['<code>messi5.JPG</code> · <code>mesi5.jpg</code> → 대소문자 · 오타도 실패'],
        notes: '<p>실행 전 발문: “네 개 중 몇 개가 성공할까요?” → messi5.jpg, lena.jpg 두 개. 대소문자만 달라도 실패한다는 점에 놀라는 학생이 많습니다.</p><p><code>== None</code> 보다 <code>is None</code> 이 올바른 비교라는 점을 짧게 언급하세요. (2분)</p>' },
      { title: 'cv.imwrite() — 저장하기',
        points: ['<code>cv.imwrite(파일이름, img)</code> → 성공 시 <code>True</code>', '확장자로 형식 결정: <code>.png</code> · <code>.jpg</code>', 'PNG 무손실 · JPG 용량 작고 약간 손실', '웹: 콘솔에 <b>다운로드 링크</b>, 다시 imread 가능'],
        notes: '<p>“저장 형식을 따로 지정하지 않아도 확장자만 보고 알아서 저장합니다.”</p><p>발문: “검출 결과처럼 정확한 값이 중요한 이미지는 PNG, JPG 중 무엇이 좋을까요?” → PNG(무손실). (2분)</p>' },
      { title: '흑백으로 저장한 뒤 다시 읽기', example: 4,
        points: ['저장 → 콘솔 링크 → 다시 읽으면 shape <code>(342, 548)</code>'],
        notes: '<p>실행 후 콘솔의 다운로드 링크를 눌러 실제 파일이 내려받아지는 것을 보여 주세요.</p><p>UNCHANGED 로 다시 읽었는데도 2차원인 이유를 물어보세요 → 애초에 흑백으로 저장했기 때문. (3분)</p>' },
      { title: 'Matplotlib 과 BGR / RGB 문제',
        points: ['Matplotlib: 여러 장 나란히 · 제목 · 축', 'OpenCV <b>BGR</b> ↔ Matplotlib <b>RGB</b> → 색 뒤바뀜', '해결: <code>cv.cvtColor(img, cv.COLOR_BGR2RGB)</code>', '흑백은 <code>cmap=\'gray\'</code> 지정'],
        warn: 'plt.title 은 영어로 — 한글은 글자가 깨질 수 있어요',
        notes: '<p>지난 시간 “BGR 경고”를 드디어 직접 겪어 보는 순간입니다. “하늘이 주황색, 오렌지가 파랗게 보이면 BGR/RGB 문제예요.”</p><p><code>img[:, :, ::-1]</code> (채널 축 뒤집기)도 같은 결과라는 점은 NumPy 에 익숙한 학생에게 덤으로 소개하세요. (3분)</p>' },
      { title: 'BGR 그대로 vs RGB 변환', example: 5,
        points: ['1행 3열 비교: 잘못된 색 · 올바른 색 · 흑백'],
        notes: '<p>발문: “첫 번째 그림에서 오렌지가 무슨 색으로 보이나요? 왜 그럴까요?” → 파랗게 보임, 빨강과 파랑 채널이 뒤바뀌어서.</p><p>세 번째 흑백 그림에서 <code>cmap=\'gray\'</code> 를 지우고 실행해 보게 하면, 녹색·노랑 색상 지도로 나오는 것을 볼 수 있습니다. (4분)</p>' },
      { title: '내 이미지로: 흑백 변환 후 저장', example: 6,
        points: ['입력 소스(샘플 · 업로드 · 📷 웹캠) 바꿔 가며 실행'],
        notes: '<p>입력 소스를 업로드한 사진이나 웹캠으로 바꾸고 다시 ▶ 실행하게 하세요. <code>cv.cvtColor(img, cv.COLOR_BGR2GRAY)</code> 는 2주차에서 자세히 배운다고만 말합니다.</p><p>my_gray.jpg 링크로 자기 사진을 내려받아 보면 “읽기 → 처리 → 보여주기 → 저장” 한 바퀴가 완성됩니다. (3분)</p>' },
      { title: '언제 무엇을 쓸까?',
        table: { head: ['목적', '도구', '주의'], rows: [
          ['결과를 빠르게 확인', '<code>cv.imshow()</code>', '웹에서는 waitKey 불필요'],
          ['여러 장 비교 · 발표 그림', 'Matplotlib <code>plt.imshow()</code>', 'RGB 변환 · cmap=gray'],
          ['결과를 파일로 남기기', '<code>cv.imwrite()</code>', '확장자로 형식 결정'],
          ['파일 읽기', '<code>cv.imread()</code>', '실패하면 None 확인'],
        ] },
        notes: '<p>실습 전에 이 표로 오늘 내용을 한 번에 묶어 주세요. 발문: “실습 2 처럼 원본과 흑백을 나란히 보여 주려면?” → Matplotlib + RGB 변환. (1분)</p>' },
    ],
    practiceNotes: [
      '<p>두 가지를 모두 바꿔야 합니다: imread 의 flag 를 <code>cv.IMREAD_GRAYSCALE</code> 로, saved 를 <code>cv.imread(\'lena_gray.png\', ...)</code> 로. shape 가 (512, 512) 로 나오면 성공입니다. 저장 결과가 True 인지도 확인하세요.</p>',
      '<p>색이 이상하면 RGB 변환을 안 한 것, 흑백이 초록·노랑으로 보이면 <code>cmap=\'gray\'</code> 를 빠뜨린 것입니다. 순회하며 두 증상을 짚어 주세요.</p>',
      '<p><code>if img is None:</code> 안에서 메시지 출력 후 <code>return None</code>. 창이 smarties.png, butterfly.jpg 두 개만 뜨고 콘솔에 “읽기 실패: no_such_file.png”가 나오면 정답입니다. 함수로 감싸는 습관이 프로젝트에서 도움이 된다고 칭찬해 주세요.</p>',
    ],
    summary: ['<code>cv.imread(파일, flag)</code>: COLOR · GRAYSCALE · UNCHANGED', '읽기 실패는 오류가 아니라 <code>None</code> → <code>is None</code> 확인', '웹에서 <code>waitKey</code> 는 즉시 -1, 창은 결과 패널에 표시', '<code>cv.imwrite</code>: 확장자로 형식, 콘솔 링크로 다운로드', 'Matplotlib 은 RGB → <code>cv.COLOR_BGR2RGB</code> 변환'],
    next: '<p>“오늘은 사진 한 장을 다뤘다면, 다음 시간에는 <b>1초에 수십 장씩 들어오는 동영상과 웹캠</b>을 다룹니다. 데스크톱의 while 루프 대신 웹에서 쓰는 <code>process(frame)</code> 방식을 배워요.”</p>',
  },
  'w1-3': {
    intro: '<p>“동영상은 사실 사진을 빠르게 넘기는 것입니다. 사진 한 장을 다룰 줄 알면 동영상도 다룰 수 있어요.” 종이 귀퉁이 그림(플립북)을 떠올리게 하며 시작하세요. 웹캠이 없는 학생도 🎞️ 샘플 동영상으로 똑같이 할 수 있다고 미리 안심시킵니다. (도입 2분)</p>',
    goalsNotes: '<p>데스크톱 튜토리얼 코드는 “읽을 수 있으면” 충분하고, 손으로 쓰는 코드는 <b>동영상 정보 읽기 · 탐색</b>과 <b>process(frame)</b> 입니다. process 는 5주 내내 쓰는 패턴이니 오늘 확실히 잡아 주세요.</p>',
    slides: [
      { title: '비디오 = 이미지(프레임)의 연속',
        points: ['<b>프레임</b>: 동영상의 한 장', '<b>FPS</b>: 1초에 보여 주는 장 수 (웹캠 보통 30)', '재생 시간 = 프레임 수 ÷ FPS', '비디오 처리 = 한 장 읽기 → 처리 → 표시 <b>반복</b>'],
        notes: '<p>발문: “30fps 로 1분짜리 영상이면 몇 장일까요?” → 1,800장. 1교시 용어 표와 연결됩니다.</p><p>“한 장을 처리하는 방법은 지난 시간 이미지 처리와 완전히 같아요. 달라지는 건 ‘반복’뿐입니다.” (2분)</p>' },
      { title: '실습용 샘플 동영상',
        table: { head: ['이름', '크기 · FPS · 프레임', '내용 · 용도'], rows: [
          ['<code>vtest.avi</code>', '768×576 · 10fps · 795', '걷는 보행자 · 움직임 검출'],
          ['<code>Megamind.avi</code>', '720×528 · 24fps · 270', '애니메이션 · 프레임 필터'],
          ['<code>cup.mp4</code>', '640×480 · 27fps · 217', '움직이는 컵 · 색 추적(2주차)'],
        ] },
        notes: '<p>입력 소스 선택 상자를 열어 🎞️ 동영상 항목을 보여 주세요. ⬆ 업로드로 내 mp4/webm 도 추가할 수 있습니다.</p><p>발문: “vtest.avi 는 몇 초짜리일까요?” → 795 ÷ 10 = 약 80초. (1분)</p>' },
      { title: '튜토리얼: 카메라 while 루프 (데스크톱)', example: 0,
        points: ['<code>VideoCapture(0)</code> → <code>while</code> { read → 처리 → imshow → <code>waitKey(1)</code> } → release'],
        notes: '<p>실행하지 않고 구조만 읽습니다. <code>ret</code> 은 성공 여부, <code>frame</code> 은 이미지, <code>waitKey(1)</code> 은 1ms 쉬며 창 갱신과 q 키 확인이라고 설명하세요.</p><p>동영상 파일은 <code>VideoCapture(\'vtest.avi\')</code> 로 이름만 바꾸면 같은 구조이고, 파일 끝에서 ret 이 False 가 됩니다. 영상 저장(VideoWriter)은 데스크톱 참고용으로 문서 보기에 있다고만 안내합니다. (4분)</p>' },
      { title: 'VideoCapture 핵심 메서드',
        table: { head: ['코드', '의미'], rows: [
          ['<code>cv.VideoCapture(0)</code> / <code>(\'vtest.avi\')</code>', '카메라 / 동영상 파일 열기'],
          ['<code>cap.isOpened()</code>', '제대로 열렸는지 확인'],
          ['<code>ret, frame = cap.read()</code>', '프레임 한 장 (ret = 성공 여부)'],
          ['<code>cap.get(cv.CAP_PROP_FPS)</code> · <code>FRAME_COUNT</code>', 'FPS · 전체 프레임 수'],
          ['<code>cap.get(cv.CAP_PROP_FRAME_WIDTH)</code> · <code>HEIGHT</code>', '프레임 너비 · 높이'],
          ['<code>cap.set(cv.CAP_PROP_POS_FRAMES, n)</code>', 'n 번 프레임으로 이동'],
        ] },
        notes: '<p>“get 으로 정보를 읽고, set 으로 위치를 바꿉니다.” <code>cap.get()</code> 은 float 를 돌려주므로 크기로 쓸 때는 <code>int()</code> 로 바꾼다는 점을 짚어 주세요. (2분)</p>' },
      { title: '웹에서는 while 루프 금지!',
        points: ['브라우저: Python 과 화면이 <b>같은 스레드</b>', '<code>while True</code> → 화면 멈춤 (300회 넘으면 중단)', '한 장만: <code>cap.read()</code> = <b>지금 재생 중인</b> 프레임', '모든 프레임: <code>def process(frame):</code> → return'],
        notes: '<p>“웹에서 무한 루프를 돌면 Python 이 화면을 그릴 틈이 없어서 페이지가 멈춰요. 그래서 반복은 웹 환경이 대신 해 줍니다.”</p><p>두 방식의 차이를 칠판에 “한 장 → cap.read / 매 프레임 → process” 로 적어 두면 좋습니다. (2분)</p>' },
      { title: '동영상 열고 정보 읽기', example: 3,
        points: ['FPS · 프레임 수 · 크기 · 재생 시간 출력 + 현재 프레임 1장'],
        notes: '<p>실행하면 오른쪽 입력 소스가 vtest 동영상으로 바뀝니다. 재생 막대로 다른 장면으로 옮긴 뒤 다시 실행해, frame 창이 그 순간으로 바뀌는지 확인시키세요.</p><p>콘솔의 재생 시간이 앞에서 계산한 약 80초와 맞는지 확인합니다. (3분)</p>' },
      { title: '원하는 위치로 이동 (seek)', example: 4,
        points: ['프레임 번호 = 초 × FPS → <code>cap.set(cv.CAP_PROP_POS_FRAMES, n)</code>'],
        notes: '<p>발문: “60초 지점은 몇 번 프레임일까요?” → 600. <code>sec</code> 를 0, 60, 75 로 바꿔 실행하게 하세요.</p><p>80초를 넘기면 읽기 실패 메시지가 나옵니다. “항상 ret 을 확인하는 이유”를 여기서 다시 강조하세요. (3분)</p>' },
      { title: 'process(frame) 의 규칙',
        points: ['🎞️ 동영상 · 📷 웹캠: <b>새 프레임마다</b> 호출', '이미지 입력: <b>한 번</b>만 호출', '<code>return 이미지</code> → result 창 · 튜플이면 여러 창', '한 번만 할 준비는 <b>함수 밖</b>, 값 유지는 <code>global</code>'],
        notes: '<p>“데스크톱 while 루프 안에 있던 ‘처리’ 부분만 함수로 떼어 낸 것이 process 예요.”</p><p>발문: “프레임 수를 세는 count 변수는 함수 안과 밖 중 어디에 둬야 할까요?” → 밖. 안에 두면 매번 0 으로 초기화됩니다. (2분)</p>' },
      { title: '흑백 + 프레임 정보 표시', example: 5,
        points: ['<code>global count</code> 로 프레임 수 누적 · putText 로 정보 표시'],
        notes: '<p>처음엔 이미지 입력이라 frame: 1 로 멈춰 있습니다. 입력 소스를 🎞️ vtest 로 바꾸면 숫자가 계속 올라가는 것을 보여 주세요. ■ 정지로 멈추는 것도 시연합니다.</p><p><code>GRAY2BGR</code> 로 다시 3채널로 바꾸는 이유 → 흑백 이미지에는 색 글자를 쓸 수 없어서. putText 는 다음 교시에 배웁니다. (4분)</p>' },
      { title: '좌우 반전과 여러 창 반환', example: 6,
        points: ['<code>cv.flip(img, 1)</code> 좌우 · <code>0</code> 상하 · <code>-1</code> 둘 다'],
        notes: '<p>“return 에 두 개를 쓰면 창이 두 개 생깁니다.” 웹캠이 있으면 손을 들어 거울 모드를 확인해 보게 하세요.</p><p>발문: “셀카 앱의 거울 모드는 flipCode 가 몇일까요?” → 1. (2분)</p>' },
      { title: '입력 소스 컨트롤 사용법',
        points: ['🎞️ 동영상: 목록에서 선택 · 재생 / 일시정지 / 탐색', '📷 웹캠: 켜기 → 브라우저 <b>카메라 권한 허용</b>', '■ 정지 → 코드 수정 → ▶ 다시 실행', '📸 스냅샷 → <code>webcam.png</code> 로 저장'],
        tip: '웹캠이 없으면 모든 웹캠 예제를 🎞️ 동영상으로 대신하면 됩니다',
        notes: '<p>웹캠 권한 팝업에서 “차단”을 누른 학생은 주소창 왼쪽 자물쇠 아이콘에서 다시 허용해야 합니다. 순회하며 확인하세요.</p><p>좌우반전 체크는 웹캠 화면을 거울처럼 보여 주는 옵션입니다. (2분)</p>' },
      { title: '웹캠에서 현재 프레임 한 장', example: 7,
        points: ['<code>VideoCapture(0)</code> 이 웹캠을 자동으로 켬 · ret 확인 필수'],
        notes: '<p>카메라가 없거나 권한을 거부하면 ret 이 False 가 되어, 코드가 현재 입력 소스로 대신합니다. “실패해도 멈추지 않게 짜는 습관”을 칭찬 포인트로 삼으세요.</p><p>snapshot.png 가 콘솔 링크로 저장되는 것도 확인합니다. (2분)</p>' },
      { title: 'process 는 가볍게!',
        points: ['1초에 <b>수십 번</b> 호출된다', '안에서 <code>imread</code> · <code>VideoCapture</code> 반복 호출 ✗', '파이썬 이중 for 문으로 픽셀 순회 ✗', '큰 영상은 <code>cv.resize</code> 로 줄여서 처리'],
        warn: '어디서든 while 로 cap.read() 를 반복하지 마세요',
        notes: '<p>발문: “process 안에서 매번 로고 이미지를 imread 하면 어떻게 될까요?” → 30fps 면 1초에 30번 파일을 읽어 영상이 끊김. 파일 읽기는 함수 밖에서 한 번만.</p><p>실습 3 에서 320×240 으로 줄이는 이유가 이것이라고 예고하세요. (2분)</p>' },
      { title: '데스크톱 코드 ↔ 웹 코드',
        table: { head: ['데스크톱 (while 루프)', '웹 실습 환경'], rows: [
          ['<code>cap = cv.VideoCapture(...)</code>', '같은 코드 (입력 소스가 바뀜)'],
          ['<code>while</code> + <code>ret, frame = cap.read()</code>', '없음 → <code>process(frame)</code> 자동 호출'],
          ['루프 안의 처리 코드', '<code>def process(frame):</code> 안에'],
          ['<code>cv.imshow(\'frame\', out)</code>', '<code>return out</code>'],
          ['<code>waitKey(1) == ord(\'q\')</code> → break', '■ 정지 · 동영상 일시정지'],
          ['<code>cap.release()</code> · destroyAllWindows', '필요 없음'],
        ] },
        notes: '<p>“반대로, 여기서 만든 process 함수는 데스크톱 while 루프 안에 그대로 넣으면 동작합니다. 4~5주차 프로젝트도 이 구조예요.”</p><p>시간이 부족하면 이 표는 실습 전 1분 안에 훑고 넘어가세요. (2분)</p>' },
    ],
    practiceNotes: [
      '<p>flip 과 cvtColor 두 줄이면 끝납니다. 입력 소스가 이미지면 한 번만 바뀌므로, 반드시 🎞️ 동영상이나 📷 웹캠으로 바꿔 확인하게 하세요. 보행자가 반대 방향으로 걸으면 성공입니다.</p>',
      '<p><code>cap.set(cv.CAP_PROP_POS_FRAMES, n)</code> 을 read 전에 넣는 것이 핵심입니다. hstack 은 높이가, vstack 은 너비가 같아야 한다는 점을 힌트로 주세요. sheet shape 가 (576, 768, 3) 이면 정답입니다.</p>',
      '<p>가장 흔한 실수는 <code>global prev</code> 누락(UnboundLocalError)과 마지막 <code>prev = gray</code> 누락(항상 첫 프레임과 비교)입니다. <code>cv.threshold</code> 는 (ret, mask) 두 값을 돌려준다는 점도 확인하세요. 웹캠이면 손을 흔들 때만 MOTION 이 떠야 합니다.</p>',
    ],
    summary: ['비디오 = 프레임의 연속, 재생 시간 = 프레임 수 ÷ FPS', '<code>ret, frame = cap.read()</code> — ret 으로 성공 여부 확인', '<code>cap.get</code> 으로 정보, <code>cap.set(CAP_PROP_POS_FRAMES)</code> 로 이동', '웹에서는 while 대신 <code>def process(frame): return 결과</code>', 'process 는 가볍게: 준비는 함수 밖, 상태는 <code>global</code>'],
    next: '<p>“오늘 process 에서 <code>cv.putText</code> 로 글자를 몇 번 썼죠? 다음 시간에는 선·사각형·원·타원·다각형·글자를 그리는 <b>그리기 함수</b>를 제대로 배웁니다. 검출 결과를 화면에 표시하는 데 꼭 필요한 도구예요.”</p>',
  },
  'w1-4': {
    intro: '<p>“영상처리로 공을 찾았다면, 사용자에게 어떻게 보여 줄까요? 공 주위에 사각형을 그리고 ‘ball’ 이라고 써 주면 되겠죠.” 오늘 배우는 그리기 함수가 모든 검출 결과 표시의 기본이라고 동기를 주세요. (도입 1분)</p>',
    goalsNotes: '<p>함수가 여러 개지만 <b>공통 인자(img, color, thickness, lineType)</b>가 같아서 금방 익숙해진다고 안내하세요. 오늘은 “좌표를 바꿔 가며 실행해 보는” 시간입니다.</p>',
    slides: [
      { title: '좌표계 다시 보기',
        points: ['원점 <code>(0, 0)</code> = <b>왼쪽 위</b>', 'x 는 오른쪽, <b>y 는 아래쪽</b>으로 증가', '그리기 함수의 점은 항상 <code>(x, y)</code> 튜플', '좌표는 <b>정수</b> → <code>int()</code> 또는 <code>//</code>'],
        warn: '배열 인덱싱 img[y, x] 와 순서가 반대입니다',
        notes: '<p>발문: “512×512 도화지에서 오른쪽 아래 끝 점의 좌표는?” → (511, 511). 0부터 시작하니까 512 가 아니라는 점을 짚으세요.</p><p>중심 좌표를 <code>w / 2</code> 로 계산하면 실수가 되어 오류가 나니 <code>w // 2</code> 를 쓰라고 미리 알려 줍니다. (2분)</p>' },
      { title: '그리기 함수의 공통 인자',
        table: { head: ['인자', '의미', '예'], rows: [
          ['<code>img</code>', '그릴 이미지 (<b>직접 수정됨</b>)', '<code>np.zeros((512, 512, 3), np.uint8)</code>'],
          ['<code>color</code>', '컬러는 <code>(B, G, R)</code>, 흑백은 숫자 하나', '<code>(255, 0, 0)</code> = 파랑'],
          ['<code>thickness</code>', '선 두께, <b>-1 이면 속 채우기</b>', '<code>3</code>, <code>-1</code>'],
          ['<code>lineType</code>', '<code>cv.LINE_8</code>(기본) · <code>cv.LINE_AA</code>(매끄러움)', '<code>cv.LINE_AA</code>'],
        ] },
        notes: '<p>“그리기 함수는 원본 배열에 바로 그립니다. 원본을 남기고 싶으면 먼저 <code>img.copy()</code> 하세요.” 사진에 주석을 달 때 중요합니다.</p><p>color 가 BGR 순서라는 점을 한 번 더 확인하세요. (2분)</p>' },
      { title: '선 그리기 cv.line', example: 0,
        points: ['<code>cv.line(img, 시작점, 끝점, color, thickness)</code>'],
        notes: '<p>실행 후 결과 창을 클릭해 크게 보고, 두 흰 선의 가장자리를 비교하게 하세요. 발문: “어느 선이 더 매끄러운가요?” → 아래쪽 LINE_AA.</p><p>대각선의 끝점을 (511, 0) 으로 바꾸면 반대 방향 대각선이 됩니다. 직접 바꿔 보게 하세요. (3분)</p>' },
      { title: '사각형과 원',
        points: ['<code>cv.rectangle(img, 왼쪽위, 오른쪽아래, color, t)</code>', '<code>cv.circle(img, 중심, 반지름, color, t)</code>', '<code>thickness=-1</code> → 속을 채운 도형', '튜토리얼: 초록 사각형 안에 꽉 찬 빨간 원'],
        notes: '<p>“사각형은 꼭짓점 두 개, 원은 중심과 반지름.” 이 두 함수가 검출 결과 표시에 가장 많이 쓰입니다.</p><p>발문: “사각형 (384, 0)~(510, 128) 안에 꽉 차는 원의 중심과 반지름은?” → 중심 (447, 63), 반지름 약 63. 예제에서 확인합니다. (2분)</p>' },
      { title: '사각형 · 원 그리기', example: 1,
        points: ['채운 원(-1)과 속이 빈 도형 비교'],
        notes: '<p>원의 thickness 를 -1 에서 3 으로 바꿔 실행해 차이를 보게 하세요. 사각형의 두 꼭짓점을 바꿔 크기를 조절하는 연습도 좋습니다. (3분)</p>' },
      { title: '타원 cv.ellipse 의 인자',
        table: { head: ['인자', '의미'], rows: [
          ['<code>center</code>', '중심 <code>(x, y)</code>'],
          ['<code>axes</code>', '<code>(가로 반지름, 세로 반지름)</code> · 같으면 원'],
          ['<code>angle</code>', '타원 전체 회전 각도 (시계 방향)'],
          ['<code>startAngle, endAngle</code>', '그릴 구간 · 0=3시, 90=6시 방향'],
        ] },
        notes: '<p>“인자가 많아 보이지만, 앞의 둘은 모양, angle 은 회전, 마지막 둘은 어디서부터 어디까지 그릴지입니다.”</p><p>발문: “0°~180° 로 그리면 위쪽 반일까요, 아래쪽 반일까요?” → y 가 아래로 증가하므로 <b>아래쪽</b> 반. 수학 그래프와 반대라 헷갈립니다. (3분)</p>' },
      { title: '타원 · 호 · 팩맨', example: 2,
        points: ['0~360 온전한 타원 · 180~360 위쪽 호 · 30~330 팩맨'],
        notes: '<p>팩맨의 입 방향을 바꾸려면 어떤 값을 바꿀지 물어보세요 → startAngle/endAngle 또는 angle.</p><p>튜토리얼 코드에서 색을 <code>255</code> 하나로 줬는데 파랑으로 나오는 이유 → (255, 0, 0) 으로 해석되기 때문. (4분)</p>' },
      { title: '다각형 cv.polylines',
        points: ['점 배열은 <code>np.int32</code> 자료형', '모양 맞추기 <code>pts.reshape((-1, 1, 2))</code>', '두 번째 인자는 리스트 <code>[pts]</code>', '<code>isClosed</code>: True 닫힌 도형 · False 꺾은선', '속 채우기는 <code>cv.fillPoly(img, [pts], color)</code>'],
        notes: '<p>“<code>-1</code> 은 ‘나머지는 알아서 계산해’라는 뜻이에요. 점이 4개면 (4, 1, 2) 가 됩니다.”</p><p>대괄호 [pts] 를 빠뜨리는 실수가 가장 흔합니다. 여러 다각형을 한 번에 그릴 수 있어서 리스트로 받는다고 설명하세요. (2분)</p>' },
      { title: '다각형과 꺾은선', example: 3,
        points: ['삼각형(닫힘) · 지그재그(열림) · 채운 오각형'],
        notes: '<p>지그재그의 <code>False</code> 를 <code>True</code> 로 바꾸면 어떻게 될지 예측 후 실행하게 하세요 → 마지막 점과 첫 점이 이어짐.</p><p>콘솔의 <code>pts shape: (4, 1, 2)</code> 도 확인합니다. (3분)</p>' },
      { title: '글자 쓰기 cv.putText',
        points: ['<code>cv.putText(img, text, org, font, scale, color, t, lineType)</code>', '<code>org</code> = 글자의 <b>왼쪽 아래</b> 기준점', '글꼴: <code>cv.FONT_HERSHEY_SIMPLEX</code> 등', '<code>fontScale</code> 배율 · <code>cv.LINE_AA</code> 권장'],
        warn: 'putText 는 한글 불가 → ??? 로 표시. 영어 · 숫자만!',
        notes: '<p>발문: “org 를 (10, 0) 으로 주면 글자가 보일까요?” → 거의 안 보임. 기준점이 왼쪽 아래라 글자가 위로 잘려 나갑니다.</p><p>한글을 넣어 보고 싶어 하는 학생이 반드시 있습니다. 미리 경고하세요. (2분)</p>' },
      { title: '튜토리얼 전체 코드 + 글꼴 비교', example: 4,
        points: ['선 · 사각형 · 원 · 타원 · 다각형 · 글자 한 장에 · 글꼴 5종'],
        notes: '<p>지금까지 배운 함수가 한 이미지에 모두 모인 튜토리얼 완성본입니다. 각 도형이 어느 코드 줄인지 짝지어 보게 하세요.</p><p>fonts 창에서 마음에 드는 글꼴을 고르게 하고, 실습 3 이름표에 써 보라고 연결합니다. (3분)</p>' },
      { title: '사진 위에 주석 달기', example: 5,
        points: ['<code>img.copy()</code> 에 그리기 · <code>cv.getTextSize</code> 로 글자 배경 상자'],
        notes: '<p>“검출 결과 표시가 바로 이런 모습이에요.” original 창은 그대로이고 annotated 창에만 그려진 이유 → copy 에 그렸기 때문.</p><p><code>getTextSize</code> 는 글자 너비·높이를 알려 줘서 배경 상자나 가운데 정렬에 씁니다. 실습 3 의 힌트이니 꼭 짚어 주세요. (3분)</p>' },
    ],
    practiceNotes: [
      '<p>고리는 thickness 를 크게(30 이상) 준 원호로 만듭니다. 끊긴 방향은 startAngle/endAngle 로 조절하니, 한 고리씩 실행해 보며 각도를 맞추게 하세요. 360 을 넘는 각도(120~420)도 쓸 수 있다는 점이 힌트입니다.</p>',
      '<p>큰 원부터 작은 원 순서로 그려야 덮어써서 과녁이 됩니다. <code>enumerate</code> 와 <code>i % 2</code> 로 색을 번갈아 고르는 아이디어를 끌어내세요. 흰 배경은 <code>np.full((400, 400, 3), 255, np.uint8)</code>.</p>',
      '<p>그리는 순서(배경 → 띠 → 글자 → 테두리)가 중요합니다. 이름 가운데 정렬은 <code>getTextSize</code> 로 너비를 구해 <code>(500 - tw) // 2</code>. 한글 이름을 쓰면 ??? 가 나오니 영문으로 쓰게 하세요.</p>',
    ],
    summary: ['좌표는 <code>(x, y)</code>, 원점은 왼쪽 위, y 는 아래로 증가', '공통 인자: <code>color(BGR)</code> · <code>thickness(-1=채우기)</code> · <code>LINE_AA</code>', '<code>line</code> · <code>rectangle</code> · <code>circle</code> · <code>ellipse(각도 구간)</code>', '<code>polylines</code>: int32, <code>reshape((-1,1,2))</code>, <code>[pts]</code>', '<code>putText</code>: org 는 왼쪽 아래, 한글 불가'],
    next: '<p>“오늘은 좌표를 코드에 직접 적어서 그렸어요. 다음 시간에는 <b>마우스로 클릭하고 드래그한 곳</b>에 그림을 그리는 페인트 브러시를 만듭니다. 오늘 배운 circle 과 rectangle 을 그대로 씁니다.”</p>',
  },
  'w1-5': {
    intro: '<p>“지금까지 코드는 위에서 아래로 한 번 실행되고 끝났어요. 오늘은 <b>사용자가 클릭할 때마다</b> 반응하는 프로그램을 만듭니다.” 그림판에서 마우스로 그리는 모습을 떠올리게 하세요. 영역 선택, 점 찍어 원근 변환 등 뒤 주차 프로젝트의 기초라고 동기를 줍니다. (도입 2분)</p>',
    goalsNotes: '<p>새 개념은 <b>콜백</b> 하나뿐입니다. 콜백의 5개 인자, 창과 콜백 연결, <code>global</code> 상태 변수 세 가지만 잡으면 오늘 예제가 모두 읽힌다고 안내하세요.</p>',
    slides: [
      { title: '콜백(callback) 함수란?',
        points: ['클릭은 <b>언제</b> 일어날지 모른다', '“일이 생기면 이 함수를 불러 줘” — 미리 <b>등록</b>', '비유: 식당 <b>진동벨</b>', '등록할 때는 함수 <b>이름만</b> 넘김 (괄호 ✗)'],
        notes: '<p>“진동벨을 받아 두면 음식이 나왔을 때 벨이 알려 주죠? 콜백도 마우스 이벤트가 생겼을 때 OpenCV 가 우리 함수를 대신 불러 줍니다.”</p><p>발문: “<code>setMouseCallback(\'image\', draw())</code> 처럼 괄호를 붙이면 무슨 일이 생길까요?” → 등록 순간 함수가 한 번 실행되고, 그 반환값(None)이 등록됨. (3분)</p>' },
      { title: '마우스 콜백의 5개 인자',
        table: { head: ['인자', '의미'], rows: [
          ['<code>event</code>', '무슨 일? (누름 · 이동 · 더블클릭 …) → <code>cv.EVENT_*</code> 와 비교'],
          ['<code>x, y</code>', '이벤트가 일어난 이미지 좌표'],
          ['<code>flags</code>', '그 순간 눌려 있던 버튼 · Ctrl · Shift 정보'],
          ['<code>param</code>', '등록할 때 넘긴 추가 데이터'],
        ] },
        notes: '<p>“<code>def on_mouse(event, x, y, flags, param):</code> 이 모양은 외워 두세요. 안 쓰는 인자가 있어도 5개를 모두 적어야 합니다.”</p><p>인자를 4개만 쓰면 콜백 호출 시 오류가 난다는 점을 미리 경고하세요. (2분)</p>' },
      { title: '마우스 이벤트 목록 출력', example: 0,
        points: ['<code>dir(cv)</code> 에서 EVENT 가 들어간 이름 찾기'],
        notes: '<p>“이벤트는 사실 숫자입니다. 코드에서는 읽기 쉽게 이름 상수를 써요.” 콘솔에서 EVENT_LBUTTONDBLCLK 가 7 인 것을 찾아보게 하세요.</p><p>리스트 컴프리헨션은 몰라도 괜찮다고 안심시키고 결과만 봅니다. (2분)</p>' },
      { title: '자주 쓰는 이벤트와 플래그',
        table: { head: ['상수', '값', '언제'], rows: [
          ['<code>cv.EVENT_MOUSEMOVE</code>', '0', '마우스 이동 (아주 자주)'],
          ['<code>cv.EVENT_LBUTTONDOWN</code> / <code>UP</code>', '1 / 4', '왼쪽 버튼 누름 / 뗌'],
          ['<code>cv.EVENT_RBUTTONDOWN</code>', '2', '오른쪽 버튼 누름'],
          ['<code>cv.EVENT_LBUTTONDBLCLK</code>', '7', '왼쪽 더블클릭'],
          ['<code>cv.EVENT_FLAG_LBUTTON</code>', '1', '(flags) 왼쪽 버튼 누른 채 이동'],
          ['<code>cv.EVENT_FLAG_CTRLKEY</code> / <code>SHIFTKEY</code>', '8 / 16', '(flags) Ctrl / Shift 누른 상태'],
        ] },
        notes: '<p>위 네 줄은 <b>event</b> 인자, 아래 두 줄은 <b>flags</b> 인자에서 쓰는 값이라는 것을 구분해 주세요.</p><p>발문: “드래그는 어떤 이벤트들의 연속일까요?” → LBUTTONDOWN → MOUSEMOVE 여러 번 → LBUTTONUP. (2분)</p>' },
      { title: '튜토리얼: 더블클릭에 원 (데스크톱)', example: 1,
        points: ['콜백 정의 → <code>setMouseCallback</code> → while 로 계속 imshow'],
        notes: '<p>실행하지 않고 구조만 봅니다. “데스크톱은 while 루프에서 계속 imshow 해야 바뀐 그림이 보이고, ESC(27) 로 종료합니다.”</p><p>다음 장에서 웹은 이 while 부분이 필요 없다는 것을 비교합니다. (2분)</p>' },
      { title: '웹 환경의 마우스 콜백',
        points: ['① <code>cv.imshow(\'image\', img)</code> 로 창 먼저', '② <code>cv.setMouseCallback(\'image\', 함수)</code>', '콜백이 끝나면 창이 <b>자동으로</b> 다시 그려짐', 'img 는 <b>제자리 수정</b> (<code>cv.circle(img, …)</code>)'],
        warn: '콜백 안에서 img = … 새 배열 대입 → 창에 반영 안 됨',
        notes: '<p>“웹에서는 while 루프 대신 콜백이 끝날 때마다 화면이 갱신됩니다. 그래서 콜백 안에서는 img 에 그리기만 하면 돼요.”</p><p>창 이름 오타(<code>\'image\'</code> vs <code>\'Image\'</code>)도 흔한 실수입니다. (2분)</p>' },
      { title: '더블클릭으로 원 그리기 (웹)', example: 2,
        points: ['창을 더블클릭 → 반지름 100 파란 원'],
        notes: '<p>실행 후 image 창을 여러 곳 더블클릭하게 하세요. 반지름을 20 으로, 색을 (0, 255, 255) 로 바꿔 다시 실행해 봅니다.</p><p>발문: “한 번 클릭으로 그려지게 하려면 무엇을 바꿀까요?” → <code>EVENT_LBUTTONDOWN</code>. (3분)</p>' },
      { title: '이벤트 관찰하기 (param 사용)', example: 3,
        points: ['클릭 위치 좌표 · BGR 값 · flags 를 콘솔에 출력'],
        notes: '<p>세 번째 인자로 넘긴 img 가 콜백의 param 으로 들어온다는 점을 코드에서 짚으세요. <code>param[y, x]</code> 는 행·열 순서입니다.</p><p>Ctrl·Shift 를 누른 채 클릭해 flags 가 8, 16 만큼 달라지는지, 더블클릭 시 LBUTTONDOWN 과 DBLCLK 가 함께 찍히는지 관찰하게 하세요. (4분)</p>' },
      { title: '드래그로 그리기: 상태 변수',
        points: ['드래그 = 누름 → 이동(여러 번) → 뗌', '<code>drawing</code>: 버튼이 눌려 있나?', '<code>ix, iy</code>: 누른 시작점 · <code>mode</code>: 사각형/원', '콜백 안에서 대입하므로 <code>global</code> 필수'],
        tip: '튜토리얼의 m 키 대신 웹에서는 우클릭이나 트랙바로 모드 전환',
        notes: '<p>“콜백은 이벤트마다 새로 불리니까, ‘지금 버튼이 눌려 있는지’를 함수 밖 변수에 기억해 둬야 해요.”</p><p>발문: “global 을 빼먹으면?” → UnboundLocalError. 튜토리얼 원본(m 키 버전)은 문서 보기에 있고, 웹에서는 waitKey 로 키를 받을 수 없어 우클릭으로 바꿨다고 설명하세요. (3분)</p>' },
      { title: '우클릭으로 모드 전환', example: 5,
        points: ['드래그: 그리기 · 우클릭: 사각형 ↔ 원 브러시'],
        notes: '<p>사각형 모드로 드래그하면 “부채꼴” 자국이 남습니다. 발문: “왜 자국이 남을까요?” → MOUSEMOVE 때마다 사각형을 계속 덧그리기 때문. 해결법은 다음 예제와 실습 3 에서.</p><p>원 브러시 모드로 이름을 써 보게 하면 반응이 좋습니다. (4분)</p>' },
      { title: '트랙바 스위치로 모드 · 브러시 크기', example: 6,
        points: ['사각형은 <b>뗄 때 한 번만</b> 그림 · 우클릭 <code>img[:] = 0</code> 지우기'],
        notes: '<p>트랙바는 다음 교시 주제지만 미리 맛보기입니다. 콜백 안에서 <code>getTrackbarPos</code> 로 매번 값을 읽는다는 점만 짚으세요.</p><p><code>img[:] = 0</code> 은 배열을 제자리에서 채우므로 창에 바로 반영됩니다. <code>img = np.zeros(...)</code> 로 쓰면 안 되는 이유와 대비시키세요. (4분)</p>' },
      { title: '마우스 프로그램의 기본 틀',
        points: ['① 데이터 준비: img, 원본 base, 상태 변수', '② 콜백: <code>if/elif</code> 로 이벤트 나누기', '③ <code>cv.imshow</code> 로 창 → ④ <code>setMouseCallback</code>', 'flags: <code>flags &amp; cv.EVENT_FLAG_LBUTTON</code> = 드래그 중'],
        notes: '<p>“영역 선택, 점 찍어 원근 변환, 색 찍어 추적… 앞으로 마우스를 쓰는 프로그램은 모두 이 틀입니다. 데스크톱에서는 여기에 while 루프만 붙이면 돼요.”</p><p>flags 와 <code>&amp;</code>(비트 AND)를 쓰면 상태 변수 없이도 드래그를 알 수 있다는 점은 실습 2 의 힌트입니다. (2분)</p>' },
      { title: '자주 하는 실수',
        points: ['콜백 인자 4개 → 반드시 <b>5개</b>', '<code>setMouseCallback(\'image\', draw())</code> → 괄호 ✗', '창 이름 오타 <code>\'image\'</code> ≠ <code>\'Image\'</code>', '<code>img = …</code> 대입 → <code>img[:] = …</code> 로'],
        notes: '<p>실습 전에 이 네 가지를 짧게 읽고 넘어가세요. 순회하다가 “그려지지 않아요”라는 학생이 있으면 이 목록을 위에서부터 확인하면 대부분 해결됩니다. (1분)</p>' },
    ],
    practiceNotes: [
      '<p>점 목록을 리스트 <code>points</code> 에 append 하고, 2개 이상일 때 <code>points[-2]</code> 와 <code>points[-1]</code> 을 잇게 하세요. 리스트는 append/clear 로 제자리 수정하므로 global 이 필요 없다는 점도 좋은 질문거리입니다. 우클릭 지우기는 <code>img[:] = 255</code>.</p>',
      '<p>조건 <code>event == cv.EVENT_MOUSEMOVE and flags &amp; cv.EVENT_FLAG_LBUTTON</code> 이 핵심입니다. 복원은 <code>img[:] = original</code> — <code>img = original.copy()</code> 로 쓰면 창에 반영되지 않는 실수를 확인하세요.</p>',
      '<p>이동할 때마다 <code>img[:] = base</code> 로 지운 뒤 상자를 다시 그리는 것이 “자국 없는” 비결입니다. 오른쪽 위에서 왼쪽 아래로 드래그하는 경우를 위해 <code>sorted</code> 로 좌표를 정렬하는지 확인하고, 크기 0 영역(그냥 클릭)도 처리했는지 물어보세요.</p>',
    ],
    summary: ['콜백 = 이벤트가 생기면 호출되도록 <b>등록</b>한 함수', '인자는 <code>(event, x, y, flags, param)</code> 5개', '웹: <code>imshow</code> 로 창 → <code>setMouseCallback</code>, while 불필요', '드래그는 상태 변수 + <code>global</code>, 또는 <code>flags</code> 로 판단', '창 반영은 제자리 수정: <code>cv.circle(img, …)</code>, <code>img[:] = …</code>'],
    next: '<p>“오늘 마지막 예제에서 트랙바로 브러시 크기를 바꿨죠? 다음 시간에는 <b>트랙바</b>를 제대로 배워서 컬러 팔레트를 만들고, 밝기·임계값 같은 숫자를 슬라이더로 실시간 조절해 봅니다.”</p>',
  },
  'w1-6': {
    intro: '<p>“영상처리에서 가장 많이 하는 일 중 하나가 ‘숫자 바꿔 보기’입니다. 임계값이 100 이 좋을까, 120 이 좋을까?” 매번 코드를 고치고 다시 실행하는 대신 슬라이더를 끌면서 결과를 보면 훨씬 빠르다는 점으로 시작하세요. (도입 2분)</p>',
    goalsNotes: '<p>함수는 <code>createTrackbar</code> 와 <code>getTrackbarPos</code> 두 개가 전부입니다. 오늘의 핵심은 웹에서 <b>“언제 값을 읽을까”</b>(방법 A · B)와 <b>정수 값을 원하는 범위로 바꾸는 요령</b>입니다.</p>',
    slides: [
      { title: '트랙바(슬라이더)는 왜 필요할까?',
        points: ['영상처리 = 숫자 바꿔 가며 <b>결과 비교</b>', '코드 수정 · 재실행 대신 <b>끌면서 바로 확인</b>', '3주차 Canny, 4~5주차 프로젝트 튜닝에 계속 사용', 'OpenCV 엔 버튼이 없음 → 최대값 1 트랙바 = <b>스위치</b>'],
        notes: '<p>발문: “볼륨 조절처럼 슬라이더로 조절하는 것, 주변에서 또 무엇이 있을까요?” → 사진 앱 밝기, 동영상 탐색 막대 등.</p><p>“0 아니면 1 만 되는 트랙바가 ON/OFF 스위치 역할을 합니다.” (2분)</p>' },
      { title: 'createTrackbar · getTrackbarPos',
        table: { head: ['인자 / 함수', '의미'], rows: [
          ['<code>trackbarName</code>', '트랙바 이름 (값을 읽을 때도 이 이름)'],
          ['<code>windowName</code>', '트랙바를 붙일 창 이름'],
          ['<code>value</code> · <code>count</code>', '초기값 · 최대값 (<b>최소는 항상 0, 정수만</b>)'],
          ['<code>onChange</code>', '값이 바뀔 때 호출할 함수 · 할 일 없으면 <code>nothing</code>'],
          ['<code>cv.getTrackbarPos(tb, win)</code>', '현재 위치 읽기'],
          ['<code>cv.setTrackbarPos(tb, win, pos)</code>', '코드로 위치 바꾸기'],
        ] },
        notes: '<p>“<code>cv.createTrackbar(\'R\', \'image\', 0, 255, nothing)</code> 를 읽으면: image 창에 R 이라는 0~255 슬라이더를 0 에서 시작하게 붙인다.”</p><p>onChange 자리에 None 을 넣으면 안 되고, <code>def nothing(x): pass</code> 를 넣는 관례를 보여 주세요. (3분)</p>' },
      { title: '튜토리얼: RGB 팔레트 (데스크톱)', example: 0,
        points: ['트랙바 R · G · B + 스위치 → while 에서 계속 읽어 <code>img[:] = [b, g, r]</code>'],
        notes: '<p>실행하지 않고 구조만 봅니다. while 루프가 계속 돌면서 네 트랙바 값을 읽고 이미지를 칠합니다.</p><p>발문: “<code>img[:] = [b, g, r]</code> 에서 왜 r 이 맨 뒤일까요?” → OpenCV 는 BGR 순서. (2분)</p>' },
      { title: '웹에서는 언제 값을 읽을까?',
        points: ['웹엔 while 루프가 없다', '<b>방법 A</b>: <code>onChange</code> 안에서 읽고 제자리 수정', '<b>방법 B</b>: <code>process(frame)</code> 안에서 읽기 (권장)', '창을 먼저 만들고 → 그 창 이름으로 트랙바'],
        notes: '<p>“A 는 슬라이더를 움직일 때 우리 함수가 불려서 그림을 다시 칠하는 방식, B 는 process 가 다시 실행될 때 최신 값을 읽는 방식입니다.”</p><p>창은 <code>cv.imshow</code> 나 <code>cv.namedWindow</code> 로 먼저 만들어야 트랙바를 붙일 수 있다는 점을 강조하세요. (2분)</p>' },
      { title: '팔레트 방법 A: onChange 제자리 수정', example: 1,
        points: ['네 트랙바 모두 <code>update</code> 연결 → 어느 것이 바뀌든 다시 칠함'],
        notes: '<p>실행 후 스위치를 1 로 올리고 R, G, B 를 움직이게 하세요. 발문: “노랑을 만들려면?” → R 255, G 255, B 0.</p><p>콜백이 끝나면 창이 자동 갱신되므로 <code>img[:] = …</code> 제자리 수정이 중요하다는 점은 지난 시간 마우스 콜백과 같습니다. (3분)</p>' },
      { title: '팔레트 방법 B: process 에서 읽기', example: 2,
        points: ['트랙바는 <code>nothing</code> · process 에서 읽어 입력 영상 위에 색 견본'],
        notes: '<p>입력 소스를 📷 웹캠이나 🎞️ 동영상으로 바꾸면 영상 위에 색 견본이 계속 표시됩니다. palette 창도 process 안에서 함께 갱신된다는 점을 보여 주세요.</p><p>초기값(0, 128, 255)을 바꿔 다시 실행해 보게 합니다. (3분)</p>' },
      { title: '정수 트랙바 값을 원하는 범위로',
        points: ['트랙바는 <b>0 이상 정수</b>만 준다', '음수: 0~200, 초기 100 → <code>pos - 100</code>', '실수: 0~30 → <code>pos / 10</code> (0.0~3.0)', '0 이면 안 될 때: <code>max(1, pos)</code>'],
        notes: '<p>발문: “-50 ~ +50 범위의 밝기 트랙바를 만들려면?” → 최대값 100, 사용할 때 pos − 50. 퀴즈에 나옵니다.</p><p>“나눗셈이나 크기 값에 0 이 들어가면 오류가 나니 max(1, pos) 로 막아요.” (2분)</p>' },
      { title: '밝기 · 대비 조절', example: 3,
        points: ['<code>cv.convertScaleAbs(frame, alpha=대비, beta=밝기)</code> → 0~255 로 자름'],
        notes: '<p>“새 값 = 원래 값 × alpha + beta, 그리고 0~255 로 잘라 줍니다.” 대비를 올려 사진이 하얗게 날아가는 지점(255 에서 잘림)을 관찰하게 하세요.</p><p>입력 소스를 어두운 사진, 웹캠, 🎞️ 동영상으로 바꿔 보게 합니다. (4분)</p>' },
      { title: '이진화 기준값 조절', example: 4,
        points: ['<code>gray &gt; t</code> → True/False → <code>astype(np.uint8) * 255</code>'],
        notes: '<p>“기준값보다 밝으면 흰색, 아니면 검정.” 1교시에서 본 2단계 양자화이자 2주차 <b>임계처리</b>의 원리입니다.</p><p>발문: “글자만 흰색으로 남기려면 invert 를 켜야 할까요?” → 입력에 따라 다름, 직접 해 보자. bool 배열은 그대로 표시할 수 없어 uint8 로 바꾼다는 점도 짚으세요. (4분)</p>' },
      { title: '트랙바 색 + 마우스 브러시 = 그림판', example: 5,
        points: ['콜백 안에서 색 · 굵기 읽기 · <code>setTrackbarPos</code> 로 초기 위치'],
        notes: '<p>“지난 시간 마우스 콜백과 오늘 트랙바를 합친 미니 그림판입니다. 4주차 웹캠 가상 페인터의 기초예요.”</p><p>드래그는 <code>flags &amp; cv.EVENT_FLAG_LBUTTON</code> 으로 판단한다는 점을 다시 확인하세요. 학생들이 그림 그리느라 시간이 늘어지기 쉬우니 3분 안에 끊으세요. (3분)</p>' },
      { title: '어떤 방식을 쓸까?',
        table: { head: ['', '방법 A · onChange', '방법 B · process'], rows: [
          ['onChange', '이미지를 다시 계산하는 함수', '<code>nothing</code>'],
          ['값을 읽는 곳', 'onChange 함수 안', '<code>process(frame)</code> 안'],
          ['결과 반영', '제자리 수정 → 창 자동 갱신', 'return 한 이미지 표시'],
          ['어울리는 용도', '팔레트 · 그림판 (내 캔버스)', '입력 이미지 · 웹캠 조절'],
        ] },
        tip: '이 과정의 기본은 방법 B — 데스크톱 while 루프 구조와 같아요',
        notes: '<p>“내가 만든 캔버스를 바꿀 땐 A, 입력 영상을 조절할 땐 B.” 앞으로 모든 튜닝 코드는 B 패턴으로 나온다고 정리하세요. (2분)</p>' },
      { title: '자주 하는 실수',
        points: ['<code>onChange</code> 에 None → 함수(<code>nothing</code>)를 넣기', '트랙바 만들기 <b>전에</b> getTrackbarPos 호출', '이름 · 창 이름의 대소문자 · 공백 불일치', '트랙바 값 0 으로 나눗셈 → <code>max(1, pos)</code>'],
        notes: '<p>“트랙바가 없습니다” 오류가 나면 이름 철자와 창 이름부터 비교하게 하세요. 실습 전에 1분 안에 읽고 넘어갑니다. (1분)</p>' },
    ],
    practiceNotes: [
      '<p>트랙바는 <code>cv.namedWindow(\'result\')</code> 뒤에 만들고, process 안에서 <code>getTrackbarPos</code> 로 읽어야 합니다. 흑백은 채널이 1개라도 그대로 return 해도 표시된다는 점을 확인하세요. 웹캠으로 바꿔 스위치를 켜고 끄게 합니다.</p>',
      '<p><code>out = frame.copy()</code> 후 <code>out[:, :, i] = 0</code> 이 핵심입니다. copy 없이 frame 을 직접 바꾸는 학생이 있는지 확인하세요. 발문: “R 만 끄면 무슨 색 느낌이 될까요?” → 청록색.</p>',
      '<p>색상 코드는 <code>\'#%02X%02X%02X\' % (r, g, b)</code> — 웹 색상은 <b>RGB 순서</b>, 카드 칠하기는 <b>BGR 순서</b>라는 차이를 짚으세요. 밝기 판단(합계 382 초과)으로 글자색이 바뀌는지 노랑·남색으로 테스트하게 합니다.</p>',
    ],
    summary: ['<code>cv.createTrackbar(이름, 창, 초기값, 최대값, onChange)</code>', '값은 0 이상 정수 → <code>pos - k</code>, <code>pos / 10</code>, <code>max(1, pos)</code> 로 변환', '방법 A: onChange 에서 제자리 수정 (캔버스)', '방법 B: <code>process</code> 안에서 <code>getTrackbarPos</code> (영상 조절, 권장)', 'onChange 는 반드시 함수 — 할 일 없으면 <code>nothing</code>'],
    next: '<p>“이제 이미지를 읽고, 보여 주고, 그리고, 마우스와 트랙바로 조작할 수 있게 됐어요. 다음 시간에는 다시 배열로 돌아가 <b>픽셀 접근, ROI(관심 영역), 채널 분리, 테두리</b> 같은 이미지 기본 연산을 익힙니다.”</p>',
  },
  'w1-7': {
    intro: '<p>“메시 사진에서 공을 잘라 다른 곳에 붙여 넣을 수 있을까요? 오늘 코드 한 줄로 해 봅니다.” 0교시에 배운 NumPy 슬라이싱이 실제 이미지 편집 도구가 된다는 점으로 시작하세요. (도입 2분)</p>',
    goalsNotes: '<p>목표가 다섯 개지만 모두 <b>“이미지 = NumPy 배열”</b>에서 나옵니다. 특히 <b>뷰(view)와 복사본(copy)</b>의 차이는 프로젝트에서 찾기 어려운 버그의 원인이 되니 꼭 짚고 넘어간다고 안내하세요.</p>',
    slides: [
      { title: '픽셀 값 읽고 바꾸기',
        points: ['컬러 <code>img[y, x]</code> → <code>[B G R]</code> 세 값', '채널 하나 <code>img[y, x, 0]</code> → B (1=G, 2=R)', '흑백 <code>gray[y, x]</code> → 밝기 값 하나', '바꾸기 <code>img[y, x] = [255, 255, 255]</code>'],
        warn: '인덱싱은 [행 y, 열 x] 순서!',
        notes: '<p>발문: “x=50, y=20 픽셀의 빨강 값을 읽는 코드는?” → <code>img[20, 50, 2]</code>. 퀴즈에도 나오니 칠판에 적어 두세요.</p><p>“픽셀 하나는 너무 작아서 바꿔도 안 보이니, 예제에서는 주변을 확대해서 봅니다.” (2분)</p>' },
      { title: '픽셀 접근과 수정', example: 0,
        points: ['픽셀 1개 흰색 + 11×11 영역 빨강 → 8배 확대로 확인'],
        notes: '<p>zoom 창에서 가운데 흰 점과 빨갛게 물든 사각형을 찾게 하세요. 확대할 때 <code>INTER_NEAREST</code> 를 써서 픽셀이 네모로 보입니다.</p><p>흑백으로 읽으면 값이 하나만 나오는 것도 콘솔에서 확인합니다. (3분)</p>' },
      { title: 'item() 과 NumPy 2 의 변화',
        points: ['<code>img.item(y, x, c)</code> → 파이썬 int 로 읽기', '<code>itemset()</code> 은 <b>제거됨</b> → <code>img[y, x, c] = v</code>', 'uint8 에 300 대입 → <b>OverflowError</b>', '계산 결과는 <code>np.clip()</code> 으로 0~255'],
        notes: '<p>“튜토리얼에 나오는 itemset 은 이 환경의 NumPy 2 에서 사라졌어요. 인터넷 코드에서 보이면 인덱싱 대입으로 바꾸면 됩니다.”</p><p>픽셀을 for 문으로 하나씩 바꾸는 코드는 매우 느리다는 점도 미리 경고하고, 다음 교시에 속도를 직접 잰다고 예고하세요. (2분)</p>' },
      { title: 'item() 으로 읽고 인덱싱으로 쓰기', example: 1,
        points: ['<code>numpy.uint8</code> vs <code>int</code> 자료형 · 범위 초과 대입 오류'],
        notes: '<p>콘솔에서 두 type 출력을 비교하고, OverflowError 메시지를 함께 읽어 보세요.</p><p>발문: “픽셀에 200 + 100 을 넣고 싶다면?” → 255 로 자르기(np.clip) 또는 다음 교시의 cv.add. (2분)</p>' },
      { title: '이미지 속성',
        table: { head: ['속성', '의미', 'messi5.jpg 컬러 / 흑백'], rows: [
          ['<code>img.shape</code>', '(높이, 너비, 채널) · 흑백은 (높이, 너비)', '(342, 548, 3) / (342, 548)'],
          ['<code>img.size</code>', '전체 원소 수 = 높이 × 너비 × 채널', '562248 / 187416'],
          ['<code>img.dtype</code>', '원소 자료형', 'uint8'],
          ['<code>img.ndim</code>', '차원 수', '3 / 2'],
        ] },
        notes: '<p>발문: “컬러 이미지의 size 는 픽셀 수일까요?” → 아니요, 채널까지 곱한 원소 수 (342 × 548 × 3 = 562,248).</p><p>“디버깅의 첫걸음은 <code>print(img.shape, img.dtype)</code>” — 많은 오류가 크기나 자료형이 예상과 달라서 생깁니다. (2분)</p>' },
      { title: '이미지 속성 확인하기', example: 2,
        points: ['<code>h, w = img.shape[:2]</code> — 컬러 · 흑백 모두 안전'],
        notes: '<p><code>h, w, c = img.shape</code> 로 쓰면 흑백 이미지에서 오류가 난다는 점을 대비해 설명하세요. <code>ndim</code> 으로 컬러/흑백을 구분하는 코드는 process 에서 유용합니다. (2분)</p>' },
      { title: '관심 영역 (ROI)',
        points: ['이미지의 <b>일부분만</b> 처리 (예: 얼굴 안에서 눈 찾기)', '<code>roi = img[y1:y2, x1:x2]</code> — 행 먼저', '붙여넣기: <code>img[…] = roi</code>', '붙여 넣을 자리의 <b>크기가 같아야</b> 함'],
        image: 'messi5.jpg', caption: '공 영역 img[280:340, 330:390] = 60×60',
        notes: '<p>“얼굴을 찾은 뒤 눈은 얼굴 영역 안에서만 찾으면 빠르고 정확하죠. 그 영역이 ROI 입니다.”</p><p>발문: “<code>img[280:340, 330:390]</code> 은 몇 × 몇 크기일까요?” → 60 × 60. (2분)</p>' },
      { title: '공 복사하기', example: 3,
        points: ['60×60 공을 <code>img[273:333, 100:160]</code> 에 붙여넣기'],
        notes: '<p>after 창에서 공이 두 개가 된 것을 확인하세요. 붙여 넣을 범위를 <code>100:170</code> 으로 바꾸면 “could not broadcast” 오류가 납니다. 일부러 오류를 내 보고 메시지를 읽게 하세요. (3분)</p>' },
      { title: '슬라이스는 복사가 아니라 “창문(view)”',
        points: ['<code>roi = img[0:100, 0:100]</code> → 원본 메모리 공유', '<code>roi[:] = 0</code> → <b>원본도</b> 검게 변함', '독립된 조각: <code>img[…].copy()</code>', '원본을 지켜야 하면 먼저 copy'],
        warn: '프로젝트에서 “원본이 왜 바뀌었지?” 버그의 1순위 원인',
        notes: '<p>“슬라이스는 원본을 들여다보는 창문이에요. 창문 너머에 페인트를 칠하면 원본 벽이 칠해집니다.”</p><p>반대로 지난 교시 마우스 콜백에서 <code>img[:] = base</code> 가 창에 반영된 것도 같은 원리라고 연결해 주세요. (2분)</p>' },
      { title: '뷰와 복사본의 차이', example: 4,
        points: ['view 에 빨강 → 원본 변함 · copy 에 파랑 → 원본 그대로'],
        notes: '<p>실행 전 발문: “img 창에서 빨간 사각형과 파란 사각형이 모두 보일까요?” → 빨강만 보임. 예측 후 실행해 확인하세요. (3분)</p>' },
      { title: '채널 분리와 병합',
        points: ['<code>b, g, r = cv.split(img)</code> · <code>cv.merge((b, g, r))</code>', '분리한 채널은 흑백으로 보임 (밝을수록 그 색 많음)', '<code>split</code> 은 느림 → <code>img[:, :, 0]</code> 인덱싱', '빨강 없애기: <code>img[:, :, 2] = 0</code>'],
        notes: '<p>“컬러 이미지는 B, G, R 흑백 이미지 세 장이 겹친 것” — 1교시 채널 이야기를 다시 떠올리게 하세요.</p><p>튜토리얼도 한 채널만 필요하면 split 대신 NumPy 인덱싱을 쓰라고 권합니다. (2분)</p>' },
      { title: 'split / merge 와 채널 인덱싱', example: 5,
        points: ['no red · only red 만들기 · 원본과 merge 결과 비교'],
        notes: '<p>발문: “잔디는 G 채널과 R 채널 중 어디서 더 밝게 보일까요?” → G. 창을 비교해 확인하게 하세요.</p><p>R 채널 창(흑백)과 only red 창(빨강)이 같은 정보를 다르게 보여 준다는 점을 짚습니다. (3분)</p>' },
      { title: '테두리 만들기 cv.copyMakeBorder',
        table: { head: ['borderType', '[1 2 3 4 5] 좌우 3칸'], rows: [
          ['<code>cv.BORDER_CONSTANT</code> (value 색)', '0 0 0 | 1 2 3 4 5 | 0 0 0'],
          ['<code>cv.BORDER_REPLICATE</code> (가장자리 반복)', '1 1 1 | 1 2 3 4 5 | 5 5 5'],
          ['<code>cv.BORDER_REFLECT</code> (거울, 가장자리 포함)', '3 2 1 | 1 2 3 4 5 | 5 4 3'],
          ['<code>cv.BORDER_REFLECT_101</code> (= DEFAULT)', '4 3 2 | 1 2 3 4 5 | 4 3 2'],
          ['<code>cv.BORDER_WRAP</code> (반대편 이어 붙임)', '3 4 5 | 1 2 3 4 5 | 1 2 3'],
        ] },
        notes: '<p>“<code>cv.copyMakeBorder(src, 위, 아래, 왼쪽, 오른쪽, 종류, value)</code>. 액자 효과에도 쓰지만, 진짜 용도는 <b>필터 계산</b>이에요. 가장자리 픽셀은 바깥 이웃이 없어서 ‘바깥에 무엇이 있다고 칠지’ 정해야 합니다.”</p><p>REFLECT 와 REFLECT_101 의 차이(가장자리 값 1 을 반복하느냐)를 숫자로 비교하게 하세요. 2주차 블러에서 다시 나옵니다. (3분)</p>' },
      { title: '테두리 종류 비교', example: 6,
        points: ['숫자 배열로 먼저 이해 → 로고에 10픽셀 테두리 6종'],
        notes: '<p>콘솔의 숫자 출력을 먼저 읽고 그림을 보세요. 로고 배경이 검정이라 그림만으로는 차이가 잘 안 보입니다.</p><p>발문: “CONSTANT 에 파랑을 줬는데 왜 빨간 테두리로 보일까요?” → Matplotlib 은 RGB 로 해석하기 때문 (2교시 복습). (3분)</p>' },
    ],
    practiceNotes: [
      '<p>공은 먼저 <code>.copy()</code> 해 두는 것이 안전합니다. 붙여 넣기 범위 <code>img[273:333, x:x + 60]</code> 의 너비가 60 인지 확인하세요. x = 460 은 460+60 = 520 &lt; 548 이라 범위 안입니다.</p>',
      '<p><code>np.zeros_like(img)</code> 로 빈 이미지를 만들고 해당 채널만 복사합니다. hstack 은 세 이미지의 높이가 같아야 하니 resize 를 먼저 하게 하세요. 결과 shape 의 너비가 원본의 1.5배인지 확인합니다.</p>',
      '<p>copyMakeBorder 를 두 번 겹쳐 적용하면 됩니다. 512 + 20×2 + 15×2 = 582 로 계산해 보게 하고, 흰색 value 를 튜플 <code>(255, 255, 255)</code> 로 주는지 확인하세요. REFLECT 결과가 사진 가장자리를 거울처럼 이어 붙인 모습인지 비교합니다.</p>',
    ],
    summary: ['픽셀: <code>img[y, x]</code> → [B G R], <code>img[y, x, c]</code> 채널 하나', '속성: <code>shape</code> · <code>size</code> · <code>dtype</code> — 디버깅의 첫걸음', 'ROI = 슬라이싱, 붙여넣기는 크기가 같아야 함', '슬라이스는 <b>뷰</b> → 원본을 지키려면 <code>.copy()</code>', '<code>cv.split/merge</code> · <code>img[:, :, c]</code> · <code>cv.copyMakeBorder</code>'],
    next: '<p>“다음 시간은 1주차 마지막입니다. 이미지끼리 <b>더하고 섞고(블렌딩)</b>, 마스크와 비트 연산으로 로고를 사진에 합성하고, for 문과 OpenCV 함수의 속도를 직접 재 봅니다. 오늘 배운 ROI 가 로고 합성에서 바로 쓰여요.”</p>',
  },
  'w1-8': {
    intro: '<p>“250 + 10 은 얼마일까요? 컴퓨터 이미지에서는 255 가 될 수도, 4 가 될 수도 있습니다.” 이 질문으로 호기심을 끌고 시작하세요. 오늘은 1주차 마지막 교시로, 마지막 실습이 1주차 전체를 묶는 미니 챌린지라고 예고합니다. (도입 2분)</p>',
    goalsNotes: '<p>덧셈(포화) → 블렌딩 → 비트 연산·로고 합성 → 성능 측정 순서입니다. 로고 합성이 가장 어려우니 시간을 넉넉히(12분) 쓰고, <b>1주차 정리와 미니 챌린지</b>에 마지막 12분을 확보하세요.</p>',
    slides: [
      { title: '이미지 덧셈: 포화 vs 모듈로',
        table: { head: ['연산', '250 + 10', '이미지에서는'], rows: [
          ['<code>cv.add(x, y)</code> <b>포화</b>', '<b>255</b> (최대값에 고정)', '밝은 곳은 흰색 유지 ✔'],
          ['NumPy <code>x + y</code> <b>모듈로</b>', '<b>4</b> (260 % 256)', '밝은 곳이 검게 뒤집힘 ✗'],
          ['<code>cv.subtract(10, 20)</code>', '<b>0</b> (최소값에 고정)', '음수 없이 검정'],
        ] },
        notes: '<p>“uint8 은 255 까지만 담을 수 있어요. OpenCV 는 넘치면 255 로 막아 주고, NumPy 는 256 으로 나눈 나머지를 남깁니다.”</p><p>두 이미지를 더할 때는 <b>크기와 자료형이 같아야</b> 한다는 조건도 함께 말해 두세요. (3분)</p>' },
      { title: 'cv.add 와 NumPy 덧셈 비교', example: 0,
        points: ['모든 픽셀 +100 → 포화(흰색) vs 모듈로(얼룩)'],
        notes: '<p>발문: “numpy + 창에서 관중석과 흰 유니폼이 왜 이상한 색이 됐을까요?” → 원래 밝았던 곳이 255 를 넘어 작은 값으로 뒤집혀서.</p><p><code>cv.add(img, 100)</code> 처럼 숫자 하나를 더하면 버전에 따라 B 채널에만 더해질 수 있으니, 같은 모양 배열을 만들거나 <code>convertScaleAbs</code> 를 쓰라고 안내하세요. (3분)</p>' },
      { title: '블렌딩 cv.addWeighted',
        points: ['두 이미지를 <b>비율</b>로 섞기 (반투명 · 전환 효과)', '<code>dst = img1·w1 + img2·w2 + gamma</code>', '<code>w1 = 1 − α</code>, <code>w2 = α</code> → α 0→1 로 전환', '크기가 달라? <code>cv.resize(img, (너비, 높이))</code>'],
        warn: 'resize 크기는 (너비, 높이) — shape (높이, 너비) 와 반대!',
        notes: '<p>“영화에서 장면이 서서히 바뀌는 페이드 효과가 바로 블렌딩이에요.”</p><p>발문: “w1 = 0.7, w2 = 0.3 이면 어느 이미지가 더 진하게 보일까요?” → img1. resize 인자 순서 실수가 아주 흔하니 warn 을 소리 내어 읽어 주세요. (2분)</p>' },
      { title: 'ml.png 와 로고 블렌딩', example: 1,
        points: ['로고를 ml.png 크기로 resize → 0.7 : 0.3 로 섞기'],
        notes: '<p>콘솔에서 resize 전후 shape 를 확인하세요. resize 를 주석 처리하고 실행하면 크기가 달라 오류가 나는 것을 보여 주면 조건이 확실히 기억됩니다.</p><p>0.7 과 0.3 을 바꿔 실행해 보게 하세요. (3분)</p>' },
      { title: '트랙바로 서서히 바뀌는 전환', example: 2,
        points: ['<code>alpha %</code> 트랙바 0~100 → <code>/ 100</code> → Linux ↔ Windows 로고'],
        notes: '<p>지난 교시 “트랙바 값을 실수로 바꾸기”의 복습입니다. 트랙바를 천천히 끌어 두 로고가 서서히 바뀌는 모습을 보여 주세요.</p><p>이 process 는 입력 frame 을 쓰지 않고 두 로고를 섞는다는 점도 짚습니다. (2분)</p>' },
      { title: '마스크와 비트 연산',
        table: { head: ['함수', '동작 (흰색=1, 검정=0)', '용도'], rows: [
          ['<code>cv.bitwise_and(a, b, mask=m)</code>', '둘 다 흰색만 · mask 0 인 곳은 0', '마스크 영역만 잘라내기'],
          ['<code>cv.bitwise_or(a, b)</code>', '하나라도 흰색이면 흰색', '영역 합치기'],
          ['<code>cv.bitwise_xor(a, b)</code>', '서로 다를 때만 흰색', '차이 영역'],
          ['<code>cv.bitwise_not(a)</code>', '흑 ↔ 백 반전', '마스크 뒤집기'],
          ['<code>cv.threshold(gray, t, 255, …)</code>', '밝기 &gt; t → 255 · <code>(ret, mask)</code>', '마스크 만들기'],
        ] },
        notes: '<p>“마스크는 ‘어디를 처리할지’를 흰색·검정으로 칠한 흑백 이미지예요. 스텐실 판을 떠올려 보세요.”</p><p>덧셈은 색이 섞이고 블렌딩은 반투명해져서, 로고 <b>모양 부분만</b> 정확히 바꾸려면 마스크가 필요하다고 동기를 주세요. (2분)</p>' },
      { title: '비트 연산 한눈에 보기', example: 3,
        points: ['사각형 A 와 원 B 의 AND · OR · XOR · NOT'],
        notes: '<p>실행 전 발문: “AND 결과는 어떤 모양일까요?” → 사각형과 원이 겹친 부분만. XOR 는 겹친 곳만 빠진 모양입니다. 예측 후 확인하세요. (3분)</p>' },
      { title: '로고 합성 5단계',
        points: ['① 로고 크기만큼 <b>ROI</b> 준비', '② <code>threshold</code> → <code>mask</code> · <code>bitwise_not</code> → <code>mask_inv</code>', '③ 배경: <code>bitwise_and(roi, roi, mask=mask_inv)</code>', '④ 로고: <code>bitwise_and(logo, logo, mask=mask)</code>', '⑤ <code>cv.add(배경, 로고)</code> → ROI 에 다시 넣기'],
        notes: '<p>“배경에 로고 모양 <b>구멍을 파고</b>, 로고는 <b>모양대로 오려서</b>, 둘을 더하면 구멍에 딱 맞게 들어갑니다.” 칠판에 그림으로 그리면 이해가 빠릅니다.</p><p>발문: “③ 결과는 어떤 모습일까요?” → 로고 모양이 검게 파인 배경 (퀴즈). (3분)</p>' },
      { title: '로고 합성 + 중간 결과 보기', example: 4,
        points: ['mask → mask_inv → img1_bg → img2_fg → res 창 순서로 확인'],
        notes: '<p>중간 창을 하나씩 가리키며 앞 장의 5단계와 짝지어 주세요. 이 교시에서 가장 중요한 예제이니 서두르지 마세요.</p><p>threshold 의 10 을 200 으로 바꾸면 마스크가 어떻게 달라지는지 실험해 보게 하면 좋습니다. 로고를 다른 위치로 옮기는 것은 실습 1 입니다. (5분)</p>' },
      { title: '성능 측정과 최적화',
        points: ['<code>e1 = cv.getTickCount()</code> … <code>e2</code>', '초 = <code>(e2 − e1) / cv.getTickFrequency()</code>', '<code>cv.useOptimized()</code> · <code>setUseOptimized(False)</code>', '조언: 반복문 ✗ · <b>벡터화</b> · 복사 줄이기'],
        notes: '<p>“640×480 웹캠 프레임은 30만 픽셀, 1초에 30장이면 900만 픽셀이에요. 코드 작성 방법에 따라 수백 배 차이가 납니다.”</p><p><code>time.time()</code>·<code>time.perf_counter()</code> 로도 같은 일을 할 수 있다고 덧붙이세요. IPython <code>%timeit</code> 비교는 문서 보기의 참고 코드에 있습니다. (2분)</p>' },
      { title: 'getTickCount 로 시간 재기', example: 5,
        points: ['medianBlur 반복 시간 · 최적화 켜기/끄기 비교'],
        notes: '<p>브라우저 환경에서는 최적화 켜기/끄기 차이가 작거나 없을 수 있다고 미리 말해 두세요. 중요한 것은 “작업 전후 틱 차이 ÷ 주파수”라는 측정 패턴입니다. (2분)</p>' },
      { title: '반복문 vs NumPy vs OpenCV 속도 대결', example: 7,
        points: ['160×120 영역에 +60 — 결과는 같고 속도는 수백 배 차이'],
        notes: '<p>실행 전 발문: “for 문은 OpenCV 보다 몇 배 느릴까요?” → 학생마다 추측을 받아 보고 결과와 비교하세요. 보통 수백 배 이상 차이가 납니다.</p><p>“640×480 이면 16배 더 커지니, process 에서 픽셀 for 문을 쓰면 영상이 멈춥니다. 이것이 ‘픽셀 반복문 금지’의 이유예요.” (3분)</p>' },
      { title: '1주차 한눈에 정리',
        table: { head: ['교시', '핵심 함수 · 문법', '기억할 점'], rows: [
          ['0 · 1 환경 · 이론', '<code>np.zeros</code>, shape, 슬라이싱', '이미지 = uint8 배열, <b>BGR</b>'],
          ['2 · 3 입출력 · 비디오', '<code>imread</code> · <code>imwrite</code> · <code>VideoCapture</code>', 'None 확인, 웹은 <code>process(frame)</code>'],
          ['4 그리기', '<code>line</code> · <code>rectangle</code> · <code>circle</code> · <code>putText</code>', '좌표 (x, y), -1 = 채우기'],
          ['5 · 6 마우스 · 트랙바', '<code>setMouseCallback</code> · <code>createTrackbar</code>', '콜백 5인자, process 안에서 읽기'],
          ['7 기본 연산', '<code>img[y, x]</code>, ROI, <code>split</code>, <code>copyMakeBorder</code>', '슬라이스는 뷰 → <code>.copy()</code>'],
          ['8 산술 · 성능', '<code>add</code> · <code>addWeighted</code> · <code>bitwise_*</code>', '포화 연산, 반복문 대신 벡터화'],
        ] },
        notes: '<p>표를 읽어 주기보다 “이름만 보고 무슨 일을 하는지 떠오르나요?”라고 물으며 몇 개를 무작위로 짚어 보세요.</p><p>이어서 실습 3 미니 챌린지가 이 함수들을 한 번에 쓰는 과제라고 연결합니다. (3분)</p>' },
    ],
    practiceNotes: [
      '<p>ROI 시작점을 <code>y0 = H - rows - 10</code>, <code>x0 = W - cols - 10</code> 으로 계산하는 것이 핵심입니다. 원본 로고가 사진보다 크면 broadcast 오류가 나므로 먼저 resize 해야 한다는 점을 힌트로 주세요.</p>',
      '<p>프레임 크기가 입력마다 달라서 명화를 <code>cv.resize(art, (w, h))</code> 로 맞춰야 합니다. (w, h) 순서를 (h, w) 로 쓰는 실수를 확인하세요. 명화 읽기는 process 밖에서 한 번만 하는지도 점검합니다.</p>',
      '<p>1주차 총정리 챌린지라 시간이 부족할 수 있습니다. 단계별로 창을 띄워 확인하며 진행하게 하고, 막히면 “ROI 복사 → 테두리 → 글자 → 로고 → 저장” 순서 중 어디까지 왔는지 묻는 방식으로 도와주세요. 완성하지 못해도 남은 단계는 과제로 이어서 하도록 안내합니다.</p>',
    ],
    summary: ['<code>cv.add</code> 는 포화(255 고정), NumPy <code>+</code> 는 모듈로', '<code>cv.addWeighted</code>: 크기를 맞춘 뒤 비율로 섞기', '마스크 + <code>bitwise_and/not</code> 으로 모양대로 합성', '시간 측정: 틱 차이 ÷ <code>getTickFrequency()</code>', '픽셀 반복문 대신 <b>NumPy · OpenCV 벡터화</b>'],
    next: '<p>“1주차 수고 많았어요! 다음 주에는 <b>HSV 색 공간</b>으로 특정 색 물체를 찾고, 이미지를 회전·변환하고, 임계처리와 블러로 이미지를 가공합니다. 오늘 쓴 <code>cv.threshold</code> 와 마스크가 바로 이어집니다.”</p>',
  },
});
